services:
  gateway:
    build:
      context: ./dockerfiles/gateway
    container_name: gateway
    restart: always
    ports:
      - '${GATEWAY_PORT_HTTP:-80}:80'
      - '${GATEWAY_PORT:-443}:443'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:16
    container_name: database
    restart: always
    ports:
      - '${POSTGRES_PORT:-20021}:5432'
    environment:
      POSTGRES_USER:     ${POSTGRES_USER:-isunfa}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-isunfa}
      POSTGRES_DB:       ${POSTGRES_DB:-isunfa}
    volumes:                       
      - database_data:/var/lib/postgresql/data

  storage:
    build:
      context: ./dockerfiles/storage
    container_name: storage
    restart: always
    ports:
      - '${STORAGE_PORT:-20022}:10014'
    volumes:
      - storage_data:/root/.ipfs

  blockchain:
    build:
      context: ./dockerfiles/blockchain
    container_name: blockchain
    restart: always
    ports:
      - '${DISCOVERY:-20023}:20023'
      - '${RPC:-20024}:20024'
    volumes:
      - blockchain_data:/root/.isuncoin

  osrm:
    image: osrm/osrm-backend:latest
    platform: linux/amd64
    container_name: osrm
    restart: always
    ports:
      - '${OSRM_PORT:-20025}:5000'
    volumes:
      - osrm_data:/data
    command: "osrm-routed --algorithm mld /data/map.osrm"

volumes:
  blockchain_data:
  database_data:
  storage_data:
  osrm_data:
