/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      aspectRatio: {
        '1/1': '1 / 1',
        '1/1.18': '1 / 1.18',
        '3/1': '3 / 1',
        '3/2': '3 / 2',
        '4/3': '4 / 3',
        '16/9': '16 / 9',
        '21/9': '21 / 9',
        0.95: '95 / 100',
        0.87: '87 / 100',
        0.75: '75 / 100',
        0.56: '56 / 100',
        1.18: '118 / 100',
      },
      colors: {
        green: {
          100: 'var(--green-100)',
          200: 'var(--green-200)',
          25: 'var(--green-25)',
          300: 'var(--green-300)',
          400: 'var(--green-400)',
          50: 'var(--green-50)',
          500: 'var(--green-500)',
          '500-10': 'var(--green-500-10)',
          '500-30': 'var(--green-500-30)',
          '500-5': 'var(--green-500-5)',
          '500-50': 'var(--green-500-50)',
          '500-70': 'var(--green-500-70)',
          600: 'var(--green-600)',
          700: 'var(--green-700)',
          800: 'var(--green-800)',
          900: 'var(--green-900)',
        },
        'navy-blue': {
          DEFAULT: 'var(--navy-blue-500)',
          100: 'var(--navy-blue-100)',
          200: 'var(--navy-blue-200)',
          25: 'var(--navy-blue-25)',
          300: 'var(--navy-blue-300)',
          400: 'var(--navy-blue-400)',
          50: 'var(--navy-blue-50)',
          500: 'var(--navy-blue-500)',
          '500-10': 'var(--navy-blue-500-10)',
          '500-30': 'var(--navy-blue-500-30)',
          '500-5': 'var(--navy-blue-500-5)',
          '500-50': 'var(--navy-blue-500-50)',
          '500-70': 'var(--navy-blue-500-70)',
          600: 'var(--navy-blue-600)',
          700: 'var(--navy-blue-700)',
          800: 'var(--navy-blue-800)',
          900: 'var(--navy-blue-900)',
        },
        neutral: {
          100: 'var(--neutral-100)',
          200: 'var(--neutral-200)',
          25: 'var(--neutral-25)',
          300: 'var(--neutral-300)',
          400: 'var(--neutral-400)',
          50: 'var(--neutral-50)',
          500: 'var(--neutral-500)',
          600: 'var(--neutral-600)',
          700: 'var(--neutral-700)',
          800: 'var(--neutral-800)',
          900: 'var(--neutral-900)',
          white: 'var(--neutral-white)',
        },
        orange: {
          100: 'var(--orange-100)',
          200: 'var(--orange-200)',
          25: 'var(--orange-25)',
          300: 'var(--orange-300)',
          400: 'var(--orange-400)',
          50: 'var(--orange-50)',
          500: 'var(--orange-500)',
          '500-10': 'var(--orange-500-10)',
          '500-30': 'var(--orange-500-30)',
          '500-5': 'var(--orange-500-5)',
          '500-50': 'var(--orange-500-50)',
          '500-70': 'var(--orange-500-70)',
          600: 'var(--orange-600)',
          700: 'var(--orange-700)',
          800: 'var(--orange-800)',
          900: 'var(--orange-900)',
        },

        red: {
          100: 'var(--red-100)',
          200: 'var(--red-200)',
          25: 'var(--red-25)',
          300: 'var(--red-300)',
          400: 'var(--red-400)',
          50: 'var(--red-50)',
          500: 'var(--red-500)',
          '500-10': 'var(--red-500-10)',
          '500-30': 'var(--red-500-30)',
          '500-5': 'var(--red-500-5)',
          '500-50': 'var(--red-500-50)',
          '500-70': 'var(--red-500-70)',
          600: 'var(--red-600)',
          700: 'var(--red-700)',
          800: 'var(--red-800)',
          900: 'var(--red-900)',
        },

        'royal-blue': {
          100: 'var(--royal-blue-100)',
          200: 'var(--royal-blue-200)',
          25: 'var(--royal-blue-25)',
          300: 'var(--royal-blue-300)',
          400: 'var(--royal-blue-400)',
          50: 'var(--royal-blue-50)',
          500: 'var(--royal-blue-500)',
          '500-10': 'var(--royal-blue-500-10)',
          '500-30': 'var(--royal-blue-500-30)',
          '500-5': 'var(--royal-blue-500-5)',
          '500-50': 'var(--royal-blue-500-50)',
          '500-70': 'var(--royal-blue-500-70)',
          600: 'var(--royal-blue-600)',
          700: 'var(--royal-blue-700)',
          800: 'var(--royal-blue-800)',
          900: 'var(--royal-blue-900)',
        },

        'support-baby': {
          100: 'var(--support-baby-100)',
          300: 'var(--support-baby-300)',
          400: 'var(--support-baby-400)',
          600: 'var(--support-baby-600)',
        },
        'support-indigo': {
          100: 'var(--support-indigo-100)',
          300: 'var(--support-indigo-300)',
          400: 'var(--support-indigo-400)',
          600: 'var(--support-indigo-600)',
        },

        'support-maple': {
          100: 'var(--support-maple-100)',
          300: 'var(--support-maple-300)',
          400: 'var(--support-maple-400)',
          600: 'var(--support-maple-600)',
        },

        'support-olive': {
          100: 'var(--support-olive-100)',
          300: 'var(--support-olive-300)',
          400: 'var(--support-olive-400)',
          600: 'var(--support-olive-600)',
        },

        'support-pink': {
          100: 'var(--support-pink-100)',
          300: 'var(--support-pink-300)',
          400: 'var(--support-pink-400)',
          600: 'var(--support-pink-600)',
        },

        'support-rose': {
          100: 'var(--support-rose-100)',
          300: 'var(--support-rose-300)',
          400: 'var(--support-rose-400)',
          600: 'var(--support-rose-600)',
        },

        'support-taro': {
          100: 'var(--support-taro-100)',
          300: 'var(--support-taro-300)',
          400: 'var(--support-taro-400)',
          600: 'var(--support-taro-600)',
        },

        yellow: {
          100: 'var(--yellow-100)',
          200: 'var(--yellow-200)',
          25: 'var(--yellow-25)',
          300: 'var(--yellow-300)',
          400: 'var(--yellow-400)',
          50: 'var(--yellow-50)',
          500: 'var(--yellow-500)',
          '500-10': 'var(--yellow-500-10)',
          '500-30': 'var(--yellow-500-30)',
          '500-5': 'var(--yellow-500-5)',
          '500-50': 'var(--yellow-500-50)',
          '500-70': 'var(--yellow-500-70)',
          600: 'var(--yellow-600)',
          700: 'var(--yellow-700)',
          800: 'var(--yellow-800)',
          900: 'var(--yellow-900)',
        },

        'shadow-lv': {
          1: 'var(--shadow-lv-1)',
          2: 'var(--shadow-lv-2)',
          3: 'var(--shadow-lv-3)',
          4: 'var(--shadow-lv-4)',
          5: 'var(--shadow-lv-5)',
        },

        'stroke-brand-primary': {
          DEFAULT: 'var(--stroke-brand-primary)',
          moderate: 'var(--stroke-brand-primary-moderate)',
          soft: 'var(--stroke-brand-primary-soft)',
        },
        'stroke-brand-secondary': {
          DEFAULT: 'var(--stroke-brand-secondary)',
          moderate: 'var(--stroke-brand-secondary-moderate)',
          soft: 'var(--stroke-brand-secondary-soft)',
        },
        'stroke-neutral': {
          invert: 'var(--stroke-neutral-invert)',
          mute: 'var(--stroke-neutral-mute)',
          primary: 'var(--stroke-neutral-primary)',
          quaternary: 'var(--stroke-neutral-quaternary)',
          secondary: 'var(--stroke-neutral-secondary)',
          'solid-dark': 'var(--stroke-neutral-solid-dark)',
          'solid-light': 'var(--stroke-neutral-solid-light)',
          tertiary: 'var(--stroke-neutral-tertiary)',
        },
        'stroke-state': {
          error: 'var(--stroke-state-error)',
          success: 'var(--stroke-state-success)',
          warning: 'var(--stroke-state-warning)',
        },

        'stroke-support': {
          baby: 'var(--stroke-support-baby)',
          green: 'var(--stroke-support-green)',
          indigo: 'var(--stroke-support-indigo)',
          maple: 'var(--stroke-support-maple)',
          pink: 'var(--stroke-support-pink)',
          rose: 'var(--stroke-support-rose)',
          taro: 'var(--stroke-support-taro)',
        },

        'surface-brand-primary': {
          DEFAULT: 'var(--surface-brand-primary)',
          10: 'var(--surface-brand-primary-10)',
          30: 'var(--surface-brand-primary-30)',
          5: 'var(--surface-brand-primary-5)',
          50: 'var(--surface-brand-primary-50)',
          70: 'var(--surface-brand-primary-70)',
          moderate: 'var(--surface-brand-primary-moderate)',
          soft: 'var(--surface-brand-primary-soft)',
        },

        'surface-brand-secondary': {
          DEFAULT: 'var(--surface-brand-secondary)',
          10: 'var(--surface-brand-secondary-10)',
          30: 'var(--surface-brand-secondary-30)',
          5: 'var(--surface-brand-secondary-5)',
          50: 'var(--surface-brand-secondary-50)',
          70: 'var(--surface-brand-secondary-70)',
          moderate: 'var(--surface-brand-secondary-moderate)',
          soft: 'var(--surface-brand-secondary-soft)',
        },

        'surface-neutral': {
          depth: 'var(--surface-neutral-depth)',
          invert: 'var(--surface-neutral-invert)',
          'main-background': 'var(--surface-neutral-main-background)',
          mute: 'var(--surface-neutral-mute)',
          'solid-dark': 'var(--surface-neutral-solid-dark)',
          'solid-light': 'var(--surface-neutral-solid-light)',
          'surface-lv1': 'var(--surface-neutral-surface-lv1)',
          'surface-lv2': 'var(--surface-neutral-surface-lv2)',
        },

        'surface-state-error': {
          DEFAULT: 'var(--surface-state-error)',
          10: 'var(--surface-state-error-10)',
          30: 'var(--surface-state-error-30)',
          5: 'var(--surface-state-error-5)',
          50: 'var(--surface-state-error-50)',
          70: 'var(--surface-state-error-70)',
          dark: 'var(--surface-state-error-dark)',
          soft: 'var(--surface-state-error-soft)',
        },

        'surface-state-success': {
          DEFAULT: 'var(--surface-state-success)',
          10: 'var(--surface-state-success-10)',
          30: 'var(--surface-state-success-30)',
          5: 'var(--surface-state-success-5)',
          50: 'var(--surface-state-success-50)',
          70: 'var(--surface-state-success-70)',
          dark: 'var(--surface-state-success-dark)',
          soft: 'var(--surface-state-success-soft)',
        },

        'surface-state-warning': {
          DEFAULT: 'var(--surface-state-warning)',
          10: 'var(--surface-state-warning-10)',
          30: 'var(--surface-state-warning-30)',
          5: 'var(--surface-state-warning-5)',
          50: 'var(--surface-state-warning-50)',
          70: 'var(--surface-state-warning-70)',
          dark: 'var(--surface-state-warning-dark)',
          soft: 'var(--surface-state-warning-soft)',
        },

        'surface-support-soft': {
          baby: 'var(--surface-support-soft-baby)',
          green: 'var(--surface-support-soft-green)',
          indigo: 'var(--surface-support-soft-indigo)',
          maple: 'var(--surface-support-soft-maple)',
          pink: 'var(--surface-support-soft-pink)',
          rose: 'var(--surface-support-soft-rose)',
          taro: 'var(--surface-support-soft-taro)',
        },

        'surface-support-strong': {
          baby: 'var(--surface-support-strong-baby)',
          green: 'var(--surface-support-strong-green)',
          indigo: 'var(--surface-support-strong-indigo)',
          maple: 'var(--surface-support-strong-maple)',
          pink: 'var(--surface-support-strong-pink)',
          rose: 'var(--surface-support-strong-rose)',
          taro: 'var(--surface-support-strong-taro)',
        },

        'text-brand-primary': {
          lv1: 'var(--text-brand-primary-lv1)',
          lv2: 'var(--text-brand-primary-lv2)',
          lv3: 'var(--text-brand-primary-lv3)',
          solid: 'var(--text-brand-primary-solid)',
        },

        'text-brand-secondary': {
          lv1: 'var(--text-brand-secondary-lv1)',
          lv2: 'var(--text-brand-secondary-lv2)',
          lv3: 'var(--text-brand-secondary-lv3)',
          solid: 'var(--text-brand-secondary-solid)',
        },

        'text-neutral': {
          invert: 'var(--text-neutral-invert)',
          link: 'var(--text-neutral-link)',
          'link-hover': 'var(--text-neutral-link-hover)',
          mute: 'var(--text-neutral-mute)',
          primary: 'var(--text-neutral-primary)',
          secondary: 'var(--text-neutral-secondary)',
          'solid-dark': 'var(--text-neutral-solid-dark)',
          'solid-light': 'var(--text-neutral-solid-light)',
          tertiary: 'var(--text-neutral-tertiary)',
        },

        'text-state-error': {
          DEFAULT: 'var(--text-state-error)',
          invert: 'var(--text-state-error-invert)',
          solid: 'var(--text-state-error-solid)',
        },

        'text-state-success': {
          DEFAULT: 'var(--text-state-success)',
          invert: 'var(--text-state-success-invert)',
          solid: 'var(--text-state-success-solid)',
        },

        'text-state-warning': {
          DEFAULT: 'var(--text-state-warning)',
          invert: 'var(--text-state-warning-invert)',
          solid: 'var(--text-state-warning-solid)',
        },

        'text-support': {
          baby: 'var(--text-support-baby)',
          green: 'var(--text-support-green)',
          indigo: 'var(--text-support-indigo)',
          maple: 'var(--text-support-maple)',
          pink: 'var(--text-support-pink)',
          rose: 'var(--text-support-rose)',
          taro: 'var(--text-support-taro)',
        },

        'accordion-surface-background': {
          'stroke-border': 'var(--accordion-stroke-border)',
          primary: 'var(--accordion-surface-background-primary)',
          secondary: 'var(--accordion-surface-background-secondary)',
          'text-paragraph': 'var(--accordion-text-paragraph)',
          'text-title': 'var(--accordion-text-title)',
          'text-title-active': 'var(--accordion-text-title-active)',
        },

        'alert-surface': {
          background: 'var(--alert-surface-background)',
          'surface-error': 'var(--alert-surface-error)',
          'surface-success': 'var(--alert-surface-success)',
          'surface-warning': 'var(--alert-surface-warning)',
          'surface-info': 'var(--alert-surface-info)',
        },

        avatar: {
          'stroke-primary': 'var(--avatar-stroke-primary)',
          'stroke-secondary': 'var(--avatar-stroke-secondary)',

          'surface-background-baby': 'var(--avatar-surface-background-baby)',
          'surface-background-green': 'var(--avatar-surface-background-green)',
          'surface-background-icon': 'var(--avatar-surface-background-icon)',
          'surface-background-indigo': 'var(--avatar-surface-background-indigo)',
          'surface-background-maple': 'var(--avatar-surface-background-maple)',
          'surface-background-number': 'var(--avatar-surface-background-number)',
          'surface-background-pink': 'var(--avatar-surface-background-pink)',
          'surface-background-placeholder': 'var(--avatar-surface-background-placeholder)',
          'surface-background-rose': 'var(--avatar-surface-background-rose)',
          'surface-background-taro': 'var(--avatar-surface-background-taro)',
          'surface-indicator--notification': 'var(--avatar-surface-indicator--notification)',
          'surface-indicator-icon': 'var(--avatar-surface-indicator-icon)',
          'surface-indicator-offline': 'var(--avatar-surface-indicator-offline)',
          'surface-indicator-online': 'var(--avatar-surface-indicator-online)',

          'text-in-dark-background': 'var(--avatar-text-in-dark-background)',
          'text-in-light-background': 'var(--avatar-text-in-light-background)',
          'text-primary': 'var(--avatar-text-primary)',
        },

        badge: {
          'stroke-error': 'var(--badge-stroke-error)',
          'stroke-success': 'var(--badge-stroke-success)',
          'stroke-warning': 'var(--badge-stroke-warning)',
          'stroke-primary': 'var(--badge-stroke-primary)',
          'stroke-secondary': 'var(--badge-stroke-secondary)',

          'surface-base-soft': 'var(--badge-surface-base-soft)',
          'surface-base-strong': 'var(--badge-surface-base-strong)',
          'surface-soft-error': 'var(--badge-surface-soft-error)',
          'surface-soft-success': 'var(--badge-surface-soft-success)',
          'surface-soft-warning': 'var(--badge-surface-soft-warning)',
          'surface-soft-primary': 'var(--badge-surface-soft-primary)',
          'surface-soft-secondary': 'var(--badge-surface-soft-secondary)',

          'surface-strong-error': 'var(--badge-surface-strong-error)',
          'surface-strong-success': 'var(--badge-surface-strong-success)',
          'surface-strong-warning': 'var(--badge-surface-strong-warning)',
          'surface-strong-primary': 'var(--badge-surface-strong-primary)',
          'surface-strong-secondary': 'var(--badge-surface-strong-secondary)',

          'text-error': 'var(--badge-text-error)',
          'text-error-solid': 'var(--badge-text-error-solid)',
          'text-invert': 'var(--badge-text-invert)',
          'text-primary': 'var(--badge-text-primary)',
          'text-secondary': 'var(--badge-text-secondary)',
          'text-primary-solid': 'var(--badge-text-primary-solid)',
          'text-secondary-solid': 'var(--badge-text-secondary-solid)',
          'text-warning': 'var(--badge-text-warning)',
          'text-warning-solid': 'var(--badge-text-warning-solid)',
          'text-success': 'var(--badge-text-success)',
          'text-success-solid': 'var(--badge-text-success-solid)',
        },

        button: {
          'stroke-disable': 'var(--button-stroke-disable)',
          'stroke-primary': 'var(--button-stroke-primary)',
          'stroke-secondary': 'var(--button-stroke-secondary)',
          'stroke-primary-hover': 'var(--button-stroke-primary-hover)',
          'stroke-secondary-hover': 'var(--button-stroke-secondary-hover)',

          'surface-soft-disable': 'var(--button-surface-soft-disable)',
          'surface-soft-primary': 'var(--button-surface-soft-primary)',
          'surface-soft-secondary': 'var(--button-surface-soft-secondary)',
          'surface-soft-primary-hover': 'var(--button-surface-soft-primary-hover)',
          'surface-soft-secondary-hover': 'var(--button-surface-soft-secondary-hover)',

          'surface-strong-disable': 'var(--button-surface-strong-disable)',
          'surface-strong-primary': 'var(--button-surface-strong-primary)',
          'surface-strong-secondary': 'var(--button-surface-strong-secondary)',
          'surface-strong-primary-hover': 'var(--button-surface-strong-primary-hover)',
          'surface-strong-secondary-hover': 'var(--button-surface-strong-secondary-hover)',

          'text-disable': 'var(--button-text-disable)',
          'text-invert': 'var(--button-text-invert)',
          'text-primary': 'var(--button-text-primary)',
          'text-secondary': 'var(--button-text-secondary)',
          'text-primary-hover': 'var(--button-text-primary-hover)',
          'text-secondary-hover': 'var(--button-text-secondary-hover)',
          'text-primary-solid': 'var(--button-text-primary-solid)',
          'text-secondary-solid': 'var(--button-text-secondary-solid)',
        },

        card: {
          'stroke-brand': 'var(--card-stroke-brand)',
          'stroke-primary': 'var(--card-stroke-primary)',

          'surface-brand-primary': 'var(--card-surface-brand-primary)',
          'surface-brand-secondary': 'var(--card-surface-brand-secondary)',
          'surface-primary': 'var(--card-surface-primary)',

          'text-highlight': 'var(--card-text-highlight)',
          'text-primary': 'var(--card-text-primary)',
          'text-secondary': 'var(--card-text-secondary)',
          'text-tertiary': 'var(--card-text-tertiary)',
          'text-title': 'var(--card-text-title)',
          'text-white': 'var(--card-text-white)',
        },

        carousel: {
          'surface-active': 'var(--carousel-surface-active)',
          'surface-background': 'var(--carousel-surface-background)',
          'surface-mute': 'var(--carousel-surface-mute)',
        },

        'chat-bubbles-stroke-bubble-outline': 'var(--chat-bubbles-stroke-bubble-outline)',
        'chat-bubbles-surface-primary': 'var(--chat-bubbles-surface-primary)',
        'chat-bubbles-surface-secondary': 'var(--chat-bubbles-surface-secondary)',
        'chat-bubbles-text-error': 'var(--chat-bubbles-text-error)',
        'chat-bubbles-text-link': 'var(--chat-bubbles-text-link)',
        'chat-bubbles-text-note': 'var(--chat-bubbles-text-note)',
        'chat-bubbles-text-primary': 'var(--chat-bubbles-text-primary)',
        'chat-bubbles-text-solid--dark': 'var(--chat-bubbles-text-solid--dark)',
        'checkbox-stroke-check-mark': 'var(--checkbox-stroke-check-mark)',
        'checkbox-stroke-disable': 'var(--checkbox-stroke-disable)',
        'checkbox-stroke-focus': 'var(--checkbox-stroke-focus)',
        'checkbox-stroke-unselected': 'var(--checkbox-stroke-unselected)',
        'checkbox-surface-disable': 'var(--checkbox-surface-disable)',
        'checkbox-surface-hover': 'var(--checkbox-surface-hover)',
        'checkbox-surface-selected': 'var(--checkbox-surface-selected)',
        'checkbox-surface-unselected': 'var(--checkbox-surface-unselected)',
        'checkbox-text-disable': 'var(--checkbox-text-disable)',
        'checkbox-text-primary': 'var(--checkbox-text-primary)',
        'checkbox-text-secondary': 'var(--checkbox-text-secondary)',
        'date-picker-stroke-input': 'var(--date-picker-stroke-input)',
        'date-picker-stroke-input-hover': 'var(--date-picker-stroke-input-hover)',
        'date-picker-stroke-selected': 'var(--date-picker-stroke-selected)',
        'date-picker-surface-calendar-background': 'var(--date-picker-surface-calendar-background)',
        'date-picker-surface-date-period': 'var(--date-picker-surface-date-period)',
        'date-picker-surface-date-selected': 'var(--date-picker-surface-date-selected)',
        'date-picker-surface-input-background': 'var(--date-picker-surface-input-background)',
        'date-picker-surface-input-selected': 'var(--date-picker-surface-input-selected)',
        'date-picker-text-default': 'var(--date-picker-text-default)',
        'date-picker-text-disable': 'var(--date-picker-text-disable)',
        'date-picker-text-input-error': 'var(--date-picker-text-input-error)',
        'date-picker-text-input-filled': 'var(--date-picker-text-input-filled)',
        'date-picker-text-input-hover': 'var(--date-picker-text-input-hover)',
        'date-picker-text-input-placeholder': 'var(--date-picker-text-input-placeholder)',
        'date-picker-text-selected': 'var(--date-picker-text-selected)',
        'date-picker-text-week': 'var(--date-picker-text-week)',
        'divider-stroke-lv-1': 'var(--divider-stroke-lv-1)',
        'divider-stroke-lv-2': 'var(--divider-stroke-lv-2)',
        'divider-stroke-lv-3': 'var(--divider-stroke-lv-3)',
        'divider-stroke-lv-4': 'var(--divider-stroke-lv-4)',
        'divider-text-lv-1': 'var(--divider-text-lv-1)',
        'divider-text-lv-2': 'var(--divider-text-lv-2)',
        'divider-text-lv-3': 'var(--divider-text-lv-3)',
        'divider-text-lv-4': 'var(--divider-text-lv-4)',
        'drag-n-drop-stroke-disable': 'var(--drag-n-drop-stroke-disable)',
        'drag-n-drop-stroke-focus': 'var(--drag-n-drop-stroke-focus)',
        'drag-n-drop-stroke-primary': 'var(--drag-n-drop-stroke-primary)',
        'drag-n-drop-surface-disable': 'var(--drag-n-drop-surface-disable)',
        'drag-n-drop-surface-hover': 'var(--drag-n-drop-surface-hover)',
        'drag-n-drop-surface-primary': 'var(--drag-n-drop-surface-primary)',
        'drag-n-drop-text-disable': 'var(--drag-n-drop-text-disable)',
        'drag-n-drop-text-error': 'var(--drag-n-drop-text-error)',
        'drag-n-drop-text-link': 'var(--drag-n-drop-text-link)',
        'drag-n-drop-text-note': 'var(--drag-n-drop-text-note)',
        'drag-n-drop-text-primary': 'var(--drag-n-drop-text-primary)',
        'dropdown-stroke-disable': 'var(--dropdown-stroke-disable)',
        'dropdown-stroke-input': 'var(--dropdown-stroke-input)',
        'dropdown-stroke-input-hover': 'var(--dropdown-stroke-input-hover)',
        'dropdown-stroke-menu': 'var(--dropdown-stroke-menu)',
        'dropdown-stroke-selected': 'var(--dropdown-stroke-selected)',
        'dropdown-surface-input-background': 'var(--dropdown-surface-input-background)',
        'dropdown-surface-input-disable': 'var(--dropdown-surface-input-disable)',
        'dropdown-surface-input-selected': 'var(--dropdown-surface-input-selected)',
        'dropdown-surface-item-hover': 'var(--dropdown-surface-item-hover)',
        'dropdown-surface-menu-background-primary':
          'var(--dropdown-surface-menu-background-primary)',
        'dropdown-surface-menu-background-secondary':
          'var(--dropdown-surface-menu-background-secondary)',
        'dropdown-surface-scrollbar': 'var(--dropdown-surface-scrollbar)',
        'dropdown-text-disable': 'var(--dropdown-text-disable)',
        'dropdown-text-head': 'var(--dropdown-text-head)',
        'dropdown-text-input-filled': 'var(--dropdown-text-input-filled)',
        'dropdown-text-input-hover': 'var(--dropdown-text-input-hover)',
        'dropdown-text-input-placeholder': 'var(--dropdown-text-input-placeholder)',
        'dropdown-text-primary': 'var(--dropdown-text-primary)',
        'dropdown-text-secondary': 'var(--dropdown-text-secondary)',
        'file-uploading-stroke-outline': 'var(--file-uploading-stroke-outline)',
        'file-uploading-surface-primary': 'var(--file-uploading-surface-primary)',
        'file-uploading-surface-secondary': 'var(--file-uploading-surface-secondary)',
        'file-uploading-text-disable': 'var(--file-uploading-text-disable)',
        'file-uploading-text-error': 'var(--file-uploading-text-error)',
        'file-uploading-text-primary': 'var(--file-uploading-text-primary)',
        'file-uploading-text-success': 'var(--file-uploading-text-success)',
        'file-uploading-text-warning': 'var(--file-uploading-text-warning)',
        'icon-surface-accent': 'var(--icon-surface-accent)',
        'icon-surface-error': 'var(--icon-surface-error)',
        'icon-surface-invert': 'var(--icon-surface-invert)',
        'icon-surface-primary': 'var(--icon-surface-primary)',
        'icon-surface-single-color-primary': 'var(--icon-surface-single-color-primary)',
        'icon-surface-single-color-secondary': 'var(--icon-surface-single-color-secondary)',
        'icon-surface-single-color-tertiary': 'var(--icon-surface-single-color-tertiary)',
        'icon-surface-solid-white': 'var(--icon-surface-solid-white)',
        'icon-surface-success': 'var(--icon-surface-success)',
        'icon-surface-warning': 'var(--icon-surface-warning)',
        'input-stroke-disable': 'var(--input-stroke-disable)',
        'input-stroke-error': 'var(--input-stroke-error)',
        'input-stroke-input': 'var(--input-stroke-input)',
        'input-stroke-input-hover': 'var(--input-stroke-input-hover)',
        'input-stroke-selected': 'var(--input-stroke-selected)',
        'input-stroke-success': 'var(--input-stroke-success)',
        'input-stroke-warning': 'var(--input-stroke-warning)',
        'input-surface-input-background': 'var(--input-surface-input-background)',
        'input-surface-input-disable': 'var(--input-surface-input-disable)',
        'input-surface-input-hover': 'var(--input-surface-input-hover)',
        'input-surface-input-selected': 'var(--input-surface-input-selected)',
        'input-text-disable': 'var(--input-text-disable)',
        'input-text-error': 'var(--input-text-error)',
        'input-text-highlight': 'var(--input-text-highlight)',
        'input-text-input-filled': 'var(--input-text-input-filled)',
        'input-text-input-hover': 'var(--input-text-input-hover)',
        'input-text-input-placeholder': 'var(--input-text-input-placeholder)',
        'input-text-primary': 'var(--input-text-primary)',
        'input-text-secondary': 'var(--input-text-secondary)',
        'input-text-success': 'var(--input-text-success)',
        'input-text-warning': 'var(--input-text-warning)',
        'link-text-disable': 'var(--link-text-disable)',
        'link-text-error': 'var(--link-text-error)',
        'link-text-error-hover': 'var(--link-text-error-hover)',
        'link-text-primary': 'var(--link-text-primary)',
        'link-text-primary-hover': 'var(--link-text-primary-hover)',
        'link-text-success': 'var(--link-text-success)',
        'link-text-success-hover': 'var(--link-text-success-hover)',
        'link-text-warning': 'var(--link-text-warning)',
        'link-text-warning-hover': 'var(--link-text-warning-hover)',
        'progress-bar-surface-bar-primary': 'var(--progress-bar-surface-bar-primary)',
        'progress-bar-surface-bar-secondary': 'var(--progress-bar-surface-bar-secondary)',
        'progress-bar-surface-base': 'var(--progress-bar-surface-base)',
        'progress-bar-text-indicator': 'var(--progress-bar-text-indicator)',
        'ratings-stroke-hover': 'var(--ratings-stroke-hover)',
        'ratings-surface-base': 'var(--ratings-surface-base)',
        'ratings-surface-hover': 'var(--ratings-surface-hover)',
        'ratings-surface-selected': 'var(--ratings-surface-selected)',
        'slider-surface-bar': 'var(--slider-surface-bar)',
        'slider-surface-base': 'var(--slider-surface-base)',
        'slider-surface-controller': 'var(--slider-surface-controller)',
        'slider-surface-controller-hover': 'var(--slider-surface-controller-hover)',
        'stepper-surface-bar-secondary': 'var(--stepper-surface-bar-secondary)',
        'stepper-surface-base': 'var(--stepper-surface-base)',
        'stepper-surface-primary': 'var(--stepper-surface-primary)',
        'stepper-text-active': 'var(--stepper-text-active)',
        'stepper-text-default': 'var(--stepper-text-default)',
        'stepper-text-finish': 'var(--stepper-text-finish)',
        'switch-surface-active': 'var(--switch-surface-active)',
        'switch-surface-base': 'var(--switch-surface-base)',
        'switch-surface-controller': 'var(--switch-surface-controller)',
        'switch-surface-disable': 'var(--switch-surface-disable)',
        'switch-text-active': 'var(--switch-text-active)',
        'switch-text-inactive': 'var(--switch-text-inactive)',
        'tabs-stroke-active': 'var(--tabs-stroke-active)',
        'tabs-stroke-default': 'var(--tabs-stroke-default)',
        'tabs-stroke-disable': 'var(--tabs-stroke-disable)',
        'tabs-stroke-hover': 'var(--tabs-stroke-hover)',
        'tabs-stroke-secondary': 'var(--tabs-stroke-secondary)',
        'tabs-stroke-solid-white': 'var(--tabs-stroke-solid-white)',
        'tabs-surface-active': 'var(--tabs-surface-active)',
        'tabs-surface-disable': 'var(--tabs-surface-disable)',
        'tabs-surface-hover': 'var(--tabs-surface-hover)',
        'tabs-text-active': 'var(--tabs-text-active)',
        'tabs-text-default': 'var(--tabs-text-default)',
        'tabs-text-disable': 'var(--tabs-text-disable)',
        'tabs-text-hover': 'var(--tabs-text-hover)',
        'tabs-text-invert': 'var(--tabs-text-invert)',
        'tabs-text-solid-white': 'var(--tabs-text-solid-white)',
        'tooltips-surface-primary': 'var(--tooltips-surface-primary)',
        'tooltips-text-default': 'var(--tooltips-text-default)',
        'tree-stroke-divider': 'var(--tree-stroke-divider)',
        'tree-stroke-icon': 'var(--tree-stroke-icon)',
        'tree-text-primary': 'var(--tree-text-primary)',

        darkPurple: '#24274A',
        darkPurple2: '#2C315B',
        darkPurple3: '#1F2243',
        darkPurple4: '#3F497A',

        lightWhite: '#FCFCFF',

        lightGreen: '#2D7E58',

        lightBlue: '#31D3F5',

        lightRed: '#C84949',

        lightOrange: '#F7931A',
        darkOrange: '#FFA600',

        lilac: '#ABA7BD',
        lilac2: '#6857d733',
        violet: '#6857D7',
        violet2: '#9747FF',

        bluePurple: '#627EEA',
        primaryBlue: '#11FFF5',
        'primaryBlue-500': 'rgba(17, 255, 245, 0.5)',
        hoverWhite: '#F0F0F0',

        primaryYellow: '#FFA502',
        primaryYellow2: '#996301',
        primaryYellow3: '#FFD892',
        primaryYellow4: '#FFA600',
        primaryYellow5: '#CC8401',
        primaryYellow6: '#997C15',

        secondaryBlue: '#001840',
        tertiaryBlue: '#304872',
        tertiaryBlue2: '#002462B2',

        lightGray: '#CED1D7',
        lightGray2: '#828998',
        lightGray3: '#C1C9D5',
        lightGray4: '#7F8A9D',
        lightGray5: '#58667F',
        lightGray6: '#CDD1D9',
        lightGray7: '#F4F5F7',

        navyBlue: '#002462',
        navyBlue2: '#27354E',
        darkBlue: '#1570EF',
        darkBlue2: '#314362',

        errorRed: '#963737',
        errorRed2: '#FED7D7',
        errorRed3: '#FB5C5C',

        successGreen: '#1E543B',
        successGreen2: '#D3F4E5',
        successGreen3: '#4BD394',

        warningYellow: '#FFCF24',

        indigo: '#8098F9',
        darkBlue3: '#0024620D',
      },
      backgroundImage: {
        web: 'url("/elements/web.svg")',
        light_up: 'url("/elements/light_up.svg")',
        light_down: 'url("/elements/light_down.svg")',
        mask: 'url("/elements/mask.svg")',
        blended_light: 'url("/elements/blended_light.svg")',
        green_light: 'url("/elements/green_light.svg")',
        shadow_01: 'url("/elements/shadow_01.svg")',
        light_01: 'url("/elements/light_01.svg")',
        light_02: 'url("/elements/light_02.svg")',
        light_03: 'url("/elements/light_03.svg")',
        light_04: 'url("/elements/light_04.svg")',
        customGradient: 'linear-gradient(180deg, rgba(0, 24, 64, 0) 10%, rgb(0, 24, 64) 85.5%)',
        contact_bg: 'url("/elements/contact_bg.svg")',
        background_pattern: 'url("/elements/background_pattern.svg")',
        green_light_left: 'url("/elements/green_light_left.svg")',
        green_light_right: 'url("/elements/green_light_right.svg")',

        purpleLinear: 'linear-gradient(180deg, #3F497A 0%, #313866 100%)',
        purpleLinear2:
          'linear-gradient(315deg, rgba(104, 87, 215, 0.30) 0%, rgba(104, 87, 215, 0.10) 100%);',

        pipe: 'url("/elements/pipe.svg")',
        neon: 'url("/animations/neon.svg")',
        101: 'url("/elements/101.png")',
        lightBalls: 'url("/elements/light_balls.svg")',
        lightBallsReverse: 'url("/elements/light_balls_reverse.svg")',

        bubbleAbove: 'url("/elements/bubble_above.svg")',
        bubbleBelow: 'url("/elements/bubble_below.svg")',

        reportCover: 'url("/documents/cover.svg")',
        contentBg: 'url("/documents/content_bg.svg"), linear-gradient(#F2F2F2,#F2F2F2)',
        headerBg: 'url("/documents/header_bg.svg"), linear-gradient(#F2F2F2,#F2F2F2)',

        spotlight: 'radial-gradient(transparent 70%, #00000080 70%)',
      },
      zIndex: {
        '-10': '-10',
        '-1': '-1',
        5: '5',
        10: '10',
        20: '20',
        30: '30',
        40: '40',
        50: '50',
        60: '60',
        70: '70',
        80: '80',
        90: '90',
        100: '100',
        10000: '10000',
      },
      fontSize: {
        xxs: ['10px', '12px'],
        xs: ['12px', '16px'],
        sm: ['14px', '20px'],
        base: ['16px', '24px'],
        lg: ['18px', '28px'],
        xl: ['20px', '28px'],
        '2xl': ['24px', '32px'],
        '3xl': ['30px', '36px'],
        '32px': ['32px', '36px'],
        '4xl': ['36px', '40px'],
        '40px': ['40px', '44px'],
        '5xl': ['42px', 1],
        '48px': ['48px', '52px'],
        '6xl': ['56px', '60px'],
        '7xl': ['72px', 1],
        '8xl': ['96px', 1],
        '9xl': ['128px', 1],

        h1: '44px',
        h2: '36px',
        h3: '32px',
        h4: '28px',
        h5: '24px',
        h6: '20px',
      },
      lineHeight: {
        h1: '52px',
        h2: '44px',
        h3: '40px',
        h4: '36px',
        h5: '32px',
        h6: '32px',
        '52px': '52px',
        '44px': '44px',
        '40px': '40px',
        '36px': '36px',
        '32px': '32px',
      },
      screens: {
        /* Info: (20240315 - Shirley) 等同於 @media (min-width: ...px) */

        iphonese: '376px',
        iphone12pro: '391px',
        iphonexr: '415px',
        iphone12promax: '431px',

        sm: '500px', // mobile
        md: '768px', // tablet
        lg: '1024px', // desktop
        xl: '1440px',
      },
      container: {
        center: true,
        padding: '1rem',
        screens: {
          sm: '320px',
          md: '768px',
          lg: '1024px',
        },
      },

      spacing: {
        /* Info: (20240315 - Shirley) 適用範圍
         * width / height / padding / margin / top / bottom / right / left */
        nonepx: 'var(--number-none)',
        '1px': 'var(--number-1)',
        '2px': 'var(--number-2)',
        '3px': 'var(--number-3)',
        '4px': 'var(--number-4)',
        '5px': 'var(--number-5)',
        '8px': 'var(--number-8)',
        '10px': 'var(--number-10)',
        '12px': 'var(--number-12)',
        '15px': 'var(--number-15)',
        '16px': 'var(--number-16)',
        '20px': 'var(--number-20)',
        '24px': 'var(--number-24)',
        '25px': 'var(--number-25)',
        '32px': 'var(--number-32)',
        '36px': 'var(--number-36)',
        '40px': 'var(--number-40)',
        '56px': 'var(--number-56)',
        '60px': 'var(--number-60)',
        '72px': 'var(--number-72)',
        '80px': 'var(--number-80)',
        '96px': 'var(--number-96)',
        '100px': 'var(--number-100)',
        '120px': 'var(--number-120)',
        fullpx: 'var(--number-full)',

        'lv-1': 'var(--spacing-lv-1)',
        'lv-2': 'var(--spacing-lv-2)',
        'lv-3': 'var(--spacing-lv-3)',
        'lv-4': 'var(--spacing-lv-4)',
        'lv-5': 'var(--spacing-lv-5)',
        'lv-6': 'var(--spacing-lv-6)',
        'lv-7': 'var(--spacing-lv-7)',
        'lv-8': 'var(--spacing-lv-8)',
        'lv-9': 'var(--spacing-lv-9)',
        'lv-10': 'var(--spacing-lv-10)',
        'lv-11': 'var(--spacing-lv-11)',
        'lv-12': 'var(--spacing-lv-12)',

        'stroke-width-lv-1': 'var(--stroke-width-lv-1)',
        'stroke-width-lv-2': 'var(--stroke-width-lv-2)',
        'stroke-width-lv-3': 'var(--stroke-width-lv-3)',
        'stroke-width-lv-4': 'var(--stroke-width-lv-4)',
        'stroke-width-lv-5': 'var(--stroke-width-lv-5)',
        'stroke-width-lv-6': 'var(--stroke-width-lv-6)',

        // 1: 'var(--number-1)',
        // 2: 'var(--number-2)',
        // 3: 'var(--number-3)',
        // 4: 'var(--number-4)',
        // 5: 'var(--number-5)',
        // 8: 'var(--number-8)',
        // 10: 'var(--number-10)',
        // 12: 'var(--number-12)',
        // 15: 'var(--number-15)',
        // 16: 'var(--number-16)',
        // 20: 'var(--number-20)',
        // 24: 'var(--number-24)',
        // 25: 'var(--number-25)',
        // 32: 'var(--number-32)',
        // 36: 'var(--number-36)',
        // 40: 'var(--number-40)',
        // 56: 'var(--number-56)',
        // 60: 'var(--number-60)',
        // 72: 'var(--number-72)',
        // 80: 'var(--number-80)',
        // 96: 'var(--number-96)',
        // 100: 'var(--number-100)',
        // 120: 'var(--number-120)',
        // fullpx: 'var(--number-full)',

        // '1px': '1px',
        // '2px': '2px',
        // '3px': '3px',
        // '4px': '4px',
        // '5px': '5px',
        '6px': '6px',
        // '8px': '8px',
        // '10px': '10px',
        // '12px': '12px',
        '14px': '14px',
        // '15px': '15px',
        // '16px': '16px',
        '17px': '17px',
        '18px': '18px',
        '19px': '19px',
        // '20px': '20px',
        '21px': '21px',
        '22px': '22px',
        '23px': '23px',
        // '24px': '24px',
        // '25px': '25px',
        '26px': '26px',
        '27px': '27px',
        '28px': '28px',
        '30px': '30px',
        // '32px': '32px',
        '33px': '33px',
        '34px': '34px',
        '35px': '35px',
        // '36px': '36px',
        '37px': '37px',
        '38px': '38px',
        '39px': '39px',
        // '40px': '40px',
        '42px': '42px',
        '44px': '44px',
        '45px': '45px',
        '46px': '46px',
        '47px': '47px',
        '48px': '48px',
        '50px': '50px',
        '52px': '52px',
        '53px': '53px',
        '54px': '54px',
        '55px': '55px',
        // '56px': '56px',
        '57px': '57px',
        '58px': '58px',
        '59px': '59px',
        // '60px': '60px',
        '61px': '61px',
        '62px': '62px',
        '63px': '63px',
        '64px': '64px',
        '65px': '65px',
        '69px': '69px',
        '70px': '70px',
        '71px': '71px',
        // '72px': '72px',
        '73px': '73px',
        '74px': '74px',
        '75px': '75px',
        '76px': '76px',
        '77px': '77px',
        // '80px': '80px',
        '81px': '81px',
        '82px': '82px',
        '83px': '83px',
        '84px': '84px',
        '85px': '85px',
        '88px': '88px',
        '90px': '90px',
        '95px': '95px',
        '98px': '98px',
        // '100px': '100px',
        '110px': '110px',
        // '120px': '120px',
        '122px': '122px',
        '125px': '125px',
        '128px': '128px',
        '130px': '130px',
        '134px': '134px',
        '140px': '140px',
        '150px': '150px',
        '160px': '160px',
        '170px': '170px',
        '180px': '180px',
        '190px': '190px',
        '200px': '200px',
        '220px': '220px',
        '225px': '225px',
        '236px': '236px',
        '240px': '240px',
        '250px': '250px',
        '254px': '254px',
        '255px': '255px',
        '256px': '256px',
        '260px': '260px',
        '270px': '270px',
        '271px': '271px',
        '278px': '278px',
        '280px': '280px',
        '281px': '281px',
        '285px': '285px',
        '288px': '288px',
        '290px': '290px',
        '296px': '296px',
        '300px': '300px',
        '310px': '310px',
        '320px': '320px',
        '330px': '330px',
        '340px': '340px',
        '350px': '350px',
        '354px': '354px',
        '360px': '360px',
        '370px': '370px',
        '372px': '372px',
        '376px': '376px',
        '380px': '380px',
        '388px': '388px',
        '390px': '390px',
        '400px': '400px',
        '410px': '410px',
        '420px': '420px',
        '430px': '430px',
        '432px': '432px',

        '438px': '438px',
        '440px': '440px',
        '450px': '450px',
        '475px': '475px',
        '479px': '479px',
        '480px': '480px',
        '500px': '500px',
        '505px': '505px',
        '510px': '510px',
        '515px': '515px',

        '520px': '520px',
        '530px': '530px',
        '540px': '540px',
        '549px': '549px',
        '550px': '550px',
        '555px': '555px',
        '560px': '560px',
        '565px': '565px',
        '570px': '570px',
        '580px': '580px',
        '590px': '590px',
        '600px': '600px',
        '620px': '620px',
        '630px': '630px',
        '640px': '640px',
        '650px': '650px',
        '660px': '660px',
        '700px': '700px',
        '726px': '726px',
        '750px': '750px',
        '800px': '800px',
        '850px': '850px',
        '865px': '865px',
        '900px': '900px',
        '950px': '950px',
        '960px': '960px',
        '1000px': '1000px',
        '1100px': '1100px',
        '1200px': '1200px',
        '1300px': '1300px',
        '1350px': '1350px',
        '1400px': '1400px',
        '1440px': '1440px',
        '1500px': '1500px',
        '1600px': '1600px',
        '1700px': '1700px',
        '1800px': '1800px',
        '1900px': '1900px',
        '1920px': '1920px',
        '2000px': '2000px',
        '0.1rem': '0.1rem',
        '0.2rem': '0.2rem',
        '1.3rem': '1.3rem',
        '1.4rem': '1.4rem',
        '1.6rem': '1.6rem',
        '1.8rem': '1.8rem',
        '2rem': '2rem',
        '2.3rem': '2.3rem',
        '2.5rem': '2.5rem',
        '3rem': '3rem',
        '3.2rem': '3.2rem',
        '3.3rem': '3.3rem',
        '3.5rem': '3.5rem',
        '4rem': '4rem',
        '5rem': '5rem',
        '6rem': '6rem',
        '6.2rem': '6.2rem',
        '7rem': '7rem',
        '8rem': '8rem',
        '9rem': '9rem',
        '10rem': '10rem',
        '11rem': '11rem',
        '12rem': '12rem',
        '13rem': '13rem',
        '14rem': '14rem',
        '15rem': '15rem',
        '16rem': '16rem',
        '17rem': '17rem',
        '18rem': '18rem',
        '19rem': '19rem',
        '20rem': '20rem',
        '21rem': '21rem',
        '22rem': '22rem',
        '23rem': '23rem',
        '24rem': '24rem',
        '25rem': '25rem',
        '26rem': '26rem',
        '28rem': '28rem',
        '30rem': '30rem',
        '32rem': '32rem',
        '34rem': '34rem',
        '35rem': '35rem',
        '36rem': '36rem',
        '38rem': '38rem',
        '40rem': '40rem',
        '42rem': '42rem',
        '44rem': '44rem',
        '46rem': '46rem',
        '48rem': '48rem',
        '50rem': '50rem',
        '52rem': '52rem',
        '56rem': '56rem',
        '60rem': '60rem',
        '64rem': '64rem',
        '68rem': '68rem',
        '70rem': '70rem',
        '71rem': '71rem',
        '72rem': '72rem',
        '73rem': '73rem',
        '74rem': '74rem',
        '75rem': '75rem',
        '76rem': '76rem',
        '78rem': '78rem',
        '80rem': '80rem',
        '82rem': '82rem',
        '84rem': '84rem',
        '86rem': '86rem',
        '88rem': '88rem',
        '90rem': '90rem',
        '92rem': '92rem',
        '94rem': '94rem',
        '96rem': '96rem',

        '8%': '8%',
        '11%': '11%',
        '14%': '14%',
        '35%': '35%',
        0.5: '50%',
        '1/2': '50%',
        '1/4': '25%',
        '1/5': '20%',
        '2/5': '40%',
        '3/5': '60%',
        '4/5': '80%',
        '1/6': '16.7%',
        '1/8': '12.5%',
        '3/8': '37.5%',
        '5/8': '62.5%',
        '7/8': '87.5%',
        '1/10': '10%',
        '2/10': '20%',
        '3/10': '30%',
        '4/10': '40%',
        '5/10': '50%',
        '6/10': '60%',
        '7/10': '70%',
        '8/10': '80%',
        '9/10': '90%',
        '10/10': '100%',
        '1/11': '9.09090909090909%',
        '2/11': '18.181818181818183%',
        '10/11': '90.909%',
        '1/12': '8.333333%',
        '1/13': '7.692307692307692%',
        '2/13': '15.384615384615385%',
        '3/13': '23.076923076923077%',
        '1/14': '7.142857142857143%',
        '1/15': '6.666666666666667%',
        '1/16': '6.25%',
        '1/3': '33.333333%',
        '80%': '80%',
        '95%': '95%',

        '80vh': '80vh',
        '90vh': '90vh',
        '95vh': '95vh',
        '100vh': '100vh',
        '120vh': '120vh',
        '140vh': '140vh',
        '150vh': '150vh',

        '10vw': '10vw',
        '20vw': '20vw',
        '30vw': '30vw',
        '40vw': '40vw',
        '45vw': '45vw',
        '50vw': '50vw',
        '55vw': '55vw',
        '60vw': '60vw',
        '65vw': '65vw',
        '70vw': '70vw',
        '75vw': '75vw',
        '80vw': '80vw',
        '85vw': '85vw',
        '90vw': '90vw',
        '95vw': '95vw',
        '100vw': '100vw',
        '120vw': '120vw',
        '140vw': '140vw',

        // Info: (20240315- Shirley) A4 尺寸
        'a4-width': '595px',
        'a4-height': '842px',
      },
      translate: {
        '19rem': '19rem',
        '36rem': '36rem',
        '-100%': '-100%',
        '-90%': '-90%',
        '-80%': '-80%',
        '-75%': '-75%',
        '-70%': '-70%',
        '-65%': '-65%',
        '-60%': '-60%',
        '-50%': '-50%',
        '-40%': '-40%',
        '-30%': '-30%',
        '-20%': '-20%',
        '-10%': '-10%',
        '10%': '10%',
        '20%': '20%',
        '30%': '30%',
        '40%': '40%',
        '50%': '50%',
        '60%': '60%',
        '70%': '70%',
        '80%': '80%',
        '90%': '90%',
        '100%': '100%',
        '120%': '120%',
        '140%': '140%',
      },
      borderWidths: {
        '1px': 'var(--stroke-width-lv-1)',
        '2px': 'var(--stroke-width-lv-2)',
        '3px': 'var(--stroke-width-lv-3)',
        '4px': 'var(--stroke-width-lv-4)',
        '5px': 'var(--stroke-width-lv-5)',
        '6px': 'var(--stroke-width-lv-6)',
      },
      // Info: 如果設定 `s`, `m`，會造成左上左下沒有圓弧角的問題，要設定 `sm`, `md` 才行 (20240424 - Shirley)
      borderRadius: {
        xxs: 'var(--radius-xxs)',
        xs: 'var(--radius-xs)',
        sm: 'var(--radius-s)',
        md: 'var(--radius-m)',
        lg: 'var(--radius-l)',
        xl: 'var(--radius-xl)',
        rounded: 'var(--radius-rounded)',
      },
      margin: {
        '8px': '8px',
        '10px': '10px',
        '55px': '55px',
        '83px': '83px',
        '88px': '88px',
        '130px': '130px',
        '1/3': '33.333333%',
        '2/3': '66.666667%',
        '1/5': '20%',
        '1/6': '16.666667%',
        '1/8': '12.5%',
        '1/10': '10%',
        '1/12': '8.333333%',
        '1/20': '5%',
        '1/25': '4%',
        '1/50': '2%',
      },
      padding: {
        '1/3': '33.333333%',
        '2/3': '66.666667%',
        '1/5': '20%',
        '1/6': '16.666667%',
        '1/8': '12.5%',
        '1/10': '10%',
        '1/12': '8.333333%',
        '1/20': '5%',
        '1/25': '4%',
        '1/50': '2%',
        '50px': '50px',
      },
      boxShadow: {
        lg: '0 4px 10px rgba(0,0,0,0.7)',
        xl: '0 4px 24px rgba(0, 0, 0, 0.40)',
        xlReverse: '0px -4px 24px rgba(0, 0, 0, 0.40)',
        xlSide: '4px 0px 24px rgba(0, 0, 0, 0.40)',
        purple: '0px 0px 6px 0px #AB50FF',
        violet:
          '0px 0px 12px 0px rgba(175, 80, 255, 0.30), 0px 0px 24px 0px rgba(175, 80, 255, 0.30) inset',

        custom1: '0px 18px 39px 0px rgba(32, 22, 93, 0.1)',
        custom2: '0px 71px 71px 0px rgba(32, 22, 93, 0.09)',
        custom3: '0px 161px 96px 0px rgba(32, 22, 93, 0.05)',
        custom4: '0px 286px 114px 0px rgba(32, 22, 93, 0.01)',
        custom5: '0px 447px 125px 0px rgba(32, 22, 93, 0)',

        dropmenu:
          '0px 166px 46px 0px var(--Shadow-Lv-1, rgba(49, 67, 98, 0.00)), 0px 106px 42px 0px var(--Shadow-Lv-2, rgba(49, 67, 98, 0.01)), 0px 60px 36px 0px var(--Shadow-Lv-3, rgba(49, 67, 98, 0.05)), 0px 27px 27px 0px var(--Shadow-Lv-4, rgba(49, 67, 98, 0.09)), 0px 7px 15px 0px var(--Shadow-Lv-5, rgba(49, 67, 98, 0.10));',
        tooltip:
          '0px 166px 46px 0px rgba(49, 67, 98, 0.00), 0px 106px 42px 0px rgba(49, 67, 98, 0.01), 0px 60px 36px 0px rgba(49, 67, 98, 0.05), 0px 27px 27px 0px rgba(49, 67, 98, 0.09), 0px 7px 15px 0px rgba(49, 67, 98, 0.10)',
        1: 'var(--shadow-lv-1)',
        2: 'var(--shadow-lv-2)',
        3: 'var(--shadow-lv-3)',
        4: 'var(--shadow-lv-4)',
        5: 'var(--shadow-lv-5)',

        sidebarMobile:
          '0px -2px 5px 0px #3143621A, 0px -6px 10px 0px #31436217, 0px -11px 13px 0px #3143620D, 0px -28px 15px 0px #31436203, 0px -50px 17px 0px #31436200',
        navbar:
          '0px 2px 5px 0px #3143621A, 0px 6px 10px 0px #31436217, 0px 11px 13px 0px #3143620D, 0px 28px 15px 0px #31436203, 0px 50px 17px 0px #31436200',

        revertBtn:
          '0px 28px 15px 0px var(--shadow-lv-2, rgba(49, 67, 98, 0.01)), 0px 11px 13px 0px var(--shadow-lv-3, rgba(49, 67, 98, 0.05)), 0px 6px 10px 0px var(--shadow-lv-4, rgba(49, 67, 98, 0.09)), 0px 2px 5px 0px var(--shadow-lv-5, rgba(49, 67, 98, 0.10))',
        scrollBtn:
          '0px 3px 7px 0px #3143621A, 0px 13px 13px 0px #31436217, 0px 30px 18px 0px #3143620D, 0px 53px 21px 0px #31436203, 0px 83px 23px 0px #31436200',
      },
      dropShadow: {
        lg: '0 4px 10px rgba(0,0,0,0.7)',
        xl: '0px 4px 24px rgba(0, 0, 0, 0.40)',
        xlReverse: '0px -4px 24px rgba(0, 0, 0, 0.40)',
        xlSide: '4px 0px 24px rgba(0, 0, 0, 0.40)',
        purple: '0 2px 10px #AB50FF',

        custom1: '0px 18px 39px 0px rgba(32, 22, 93, 0.1)',
        custom2: '0px 71px 71px 0px rgba(32, 22, 93, 0.09)',
        custom3: '0px 161px 96px 0px rgba(32, 22, 93, 0.05)',
        custom4: '0px 286px 114px 0px rgba(32, 22, 93, 0.01)',
        custom5: '0px 447px 125px 0px rgba(32, 22, 93, 0)',

        '3xl': '0 35px 35px rgba(0, 0, 0, 0.25)',
        '4xl': ['0 35px 35px rgba(0, 0, 0, 0.25)', '0 45px 65px rgba(0, 0, 0, 0.15)'],
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif', 'ui-sans-serif', 'system-ui'],
        roboto: ['Roboto', 'sans-serif', 'ui-sans-serif', 'system-ui'],
        barlow: ['Barlow', 'sans-serif', 'ui-sans-serif', 'system-ui'],
      },
      maxWidth: {
        '80px': '80px',
        '140px': '140px',
        '248px': '248px',
        '250px': '250px',
        '260px': '260px',
        '280px': '280px',
        '300px': '300px',
        '400px': '400px',
      },
      minWidth: {
        '200px': '200px',
      },
      maxHeight: {
        '230px': '230px',
        '500px': '500px',
      },
      minHeight: {
        fit: 'fit-content',
        '200px': '200px',
        '320px': '320px',
      },
      gridTemplateRows: {
        0: 'repeat(1, minmax(0px, 0fr))',
      },
      transitionProperty: {
        grid: 'grid-template-rows',
      },
      rotate: {
        135: '135deg',
        40: '40deg',
      },
      borderWidth: {
        '0.5px': '0.5px',
        '3px': '3px',
        '5px': '5px',
      },
      backgroundSize: {
        150: '150%',
        50: '50%',
      },
      backgroundPosition: {
        'top-4': 'center top -2.5rem',
        'top-10': 'center top -10rem right -2.5rm',
        // 'right-4': 'right -2.5rem center',
      },
      keyframes: {
        slideBottomToTop: {
          '0%': { transform: 'translateY(100%)' },
          '100%': { transform: 'translateY(0)' },
        },
        slideLeftToRight: {
          '0%': { transform: 'translateX(-120%)' },
          '100%': { transform: 'translateX(0)' },
        },
        slideRightBottomToCenter: {
          '0%': { transform: 'translate(100%, 100%)' },
          '100%': { transform: 'translate(0, 0)' },
        },
        slideRightToCenter: {
          '0%': { transform: 'translateX(10%)' },
          '100%': { transform: 'translateX(0)' },
        },
        loading: {
          '0%': { transform: 'translateX(-80%)' },
          '100%': { transform: 'translateX(120%)' },
        },
      },
      animation: {
        slideBottomToTop: 'slideBottomToTop 1s ease-out forwards',
        slideLeftToRight: 'slideLeftToRight 1s ease-out forwards',
        slideRightBottomToCenter: 'slideRightBottomToCenter 1s ease-out forwards',
        slideRightToCenter: 'slideRightToCenter 1s ease-out forwards',
        spinFast: 'spin 1s linear infinite',
        loading: 'loading 1.5s infinite',
      },

      content: {
        checked: '"✔"',
      },
    },
  },
  plugins: [],
};
