import { IAggregatedDocumentResult } from "@/skills/utils/document_parser_db_sync";
import { UniversalAccountTag, CountryCode } from "@/constants/enums";
import { MoneyUtil } from "@/lib/utils/money";

export class TaxStrategyService {
  /**
   * Info: (20260527 - Tzuhan) [REFACTOR] Strategy Pattern for Tax Reverse Charge
   * Apply Reverse Charge Strategy for foreign digital services based on CountryCode.
   *
   * @param payload The original payload generated by AI
   * @param countryCode The country code of the account book
   * @returns Modified payload with reverse charge tax lines added if applicable
   */
  public static applyReverseChargeIfApplicable(
    payload: IAggregatedDocumentResult,
    countryCode: CountryCode,
  ): IAggregatedDocumentResult {
    const voucherBase = payload.voucherBase;
    if (!voucherBase) {
      return payload;
    }

    // Info: (20260527 - Tzuhan) Strategy Router
    switch (countryCode) {
      case CountryCode.TW:
        return this.applyTaiwanStrategy(payload);
      case CountryCode.EU:
        // Info: (20260527 - Tzuhan) [AUDIT] 歐盟稅務極度複雜 (17%~27%)，暫停硬算，依賴使用者或未來引擎補齊
        return this.applyEuStrategy(payload);
      default:
        // Info: (20260527 - Tzuhan) 其他國家暫無逆向課稅實作
        return payload;
    }
  }

  private static isExpenseDeductible(category: string): boolean {
    if (!category) return true;
    // Info: (20260527 - Tzuhan) 避免窮舉 (Avoid Exhaustive Enumeration)
    // Info: (20260527 - Tzuhan) 透過語意模式匹配 (Pattern Matching)，只要科目包含特定交際、福利等關鍵字即自動攔截，無須窮舉所有 Enum
    const nonDeductiblePatterns = [
      /ENTERTAINMENT/i,
      /BENEFIT/i,
      /DONATION/i,
      /MEAL/i,
      /PENALTY/i
    ];
    return !nonDeductiblePatterns.some(regex => regex.test(category));
  }

  private static applyTaiwanStrategy(
    payload: IAggregatedDocumentResult,
  ): IAggregatedDocumentResult {
    const voucherBase = payload.voucherBase!;

    // Info: (20260526 - Tzuhan) In Taiwan, valid local tax IDs are strictly 8 digits
    const isTaiwanTaxId = /^\d{8}$/.test(voucherBase.vendorTaxId || "");

    // Info: (20260526 - Tzuhan) Detect foreign software/IT services (reverse charge target)
    const isSoftwareOrIT =
      voucherBase.vendor?.toLowerCase().includes("adobe") ||
      voucherBase.vendor?.toLowerCase().includes("aws") ||
      voucherBase.vendor?.toLowerCase().includes("google") ||
      voucherBase.vendor?.toLowerCase().includes("microsoft") ||
      voucherBase.fallbackCategory === "Software" ||
      voucherBase.fallbackCategory === "Information Technology";

    if (!isTaiwanTaxId && isSoftwareOrIT) {
      console.log(
        `[TaxStrategyService] Reverse charge activated for foreign vendor: ${voucherBase.vendor} (${voucherBase.vendorTaxId})`,
      );

      const totalAmountStr = MoneyUtil.parseInput(
        String(voucherBase.totalAmount || "0"),
      );
      if (MoneyUtil.toDecimal(totalAmountStr).greaterThan(0)) {
        // Info: (20260527 - Tzuhan) Calculate 5% reverse charge tax using high-precision MoneyUtil, strictly avoid Number casting
        const taxAmountStr = MoneyUtil.multiply(totalAmountStr, "0.05");
        const taxAmountDecimal = MoneyUtil.toDecimal(taxAmountStr).toDecimalPlaces(0, 1); // Round half up
        const taxAmountFinalStr = taxAmountDecimal.toString();

        if (taxAmountDecimal.greaterThan(0)) {
          if (!payload.voucherLines) {
            payload.voucherLines = { lines: [] };
          }
          if (!payload.voucherLines.lines) {
            payload.voucherLines.lines = [];
          }

          // Info: (20260527 - Tzuhan) [AUDIT] Deductibility Check for Reverse Charge
          // Info: (20260527 - Tzuhan) 抓取主費用以判斷是否具備扣抵資格
          const debitLines = payload.voucherLines.lines.filter(l => l.isDebit);
          const primaryExpenseLine = debitLines.sort((a, b) => 
            MoneyUtil.toDecimal(String(b.amount || "0")).minus(MoneyUtil.toDecimal(String(a.amount || "0"))).toNumber()
          )[0];
          
          const isDeductible = primaryExpenseLine 
             ? this.isExpenseDeductible(primaryExpenseLine.semanticCategory || "")
             : true;

          const capitalizedCategory = !isDeductible && primaryExpenseLine
             ? primaryExpenseLine.semanticCategory
             : UniversalAccountTag.INPUT_TAX;

          // Info: (20260526 - Tzuhan) In reverse charge, we book both input tax (Debit) and output tax (Credit) simultaneously
          // Info: (20260526 - Tzuhan) Debit: 進項稅額 (Input Tax) or Capitalized Expense
          payload.voucherLines.lines.push({
            particular: isDeductible
              ? `境外電商營業稅 (Reverse Charge Input Tax) - ${voucherBase.vendor}`
              : `境外電商營業稅 (Non-deductible, Capitalized) - ${voucherBase.vendor}`,
            amount: taxAmountFinalStr,
            accountingCode: "",
            semanticCategory: capitalizedCategory || UniversalAccountTag.INPUT_TAX,
            isDebit: true,
          });

          // Info: (20260526 - Tzuhan) Credit: 銷項稅額 (Output Tax)
          payload.voucherLines.lines.push({
            particular: `境外電商營業稅 (Reverse Charge Output Tax) - ${voucherBase.vendor}`,
            amount: taxAmountFinalStr,
            accountingCode: "",
            semanticCategory: UniversalAccountTag.OUTPUT_TAX,
            isDebit: false,
          });

          voucherBase.aiNote =
            (voucherBase.aiNote || "") +
            `\n[TaxStrategyService] Auto-applied 5% reverse charge for foreign digital service (Tax Amount: ${taxAmountFinalStr}).` +
            (!isDeductible ? " Note: Tax capitalized into expense due to non-deductibility." : "");
        }
      }
    }

    return payload;
  }

  private static applyEuStrategy(
    payload: IAggregatedDocumentResult,
  ): IAggregatedDocumentResult {
    const voucherBase = payload.voucherBase!;
    // Info: (20260527 - Tzuhan) EU Strategy: Do not apply hardcoded 5% Taiwan rate.
    // 若未來需擴充，可在此處調用 EU Vat Validation API。目前標記 Warning 給前端。
    const isForeign = !/^[A-Z]{2}[A-Z0-9]+$/.test(
      voucherBase.vendorTaxId || "",
    );
    if (isForeign) {
      voucherBase.aiNote =
        (voucherBase.aiNote || "") +
        `\n[TaxStrategyService] EU VAT Reverse Charge might be applicable for foreign vendor ${voucherBase.vendorTaxId}. Please review manually.`;
    }
    return payload;
  }
}
