-- AlterEnum
ALTER TYPE "TeamPlanType" ADD VALUE 'TRIAL';

INSERT INTO team_plan (type, plan_name, price, extra_member_price, created_at, updated_at)
VALUES ('TRIAL', 'Trial Plan', 0, NULL, EXTRACT(EPOCH FROM NOW())::INT, EXTRACT(EPOCH FROM NOW())::INT);

INSERT INTO team_plan_feature (plan_id, feature_key, feature_value, created_at, updated_at)
VALUES
  ((SELECT id FROM team_plan WHERE type = 'PROFESSIONAL'), 'CLOUD_STORAGE', '1TB', EXTRACT(EPOCH FROM NOW())::INT, EXTRACT(EPOCH FROM NOW())::INT),
  ((SELECT id FROM team_plan WHERE type = 'PROFESSIONAL'), 'AI_ASSISTANT', 'UNLIMITED_CAPACITY', EXTRACT(EPOCH FROM NOW())::INT, EXTRACT(EPOCH FROM NOW())::INT),
  ((SELECT id FROM team_plan WHERE type = 'PROFESSIONAL'), 'MATCHMAKING_PLATFORM', 'POST_TASK_REQUIREMENTS', EXTRACT(EPOCH FROM NOW())::INT, EXTRACT(EPOCH FROM NOW())::INT),
  ((SELECT id FROM team_plan WHERE type = 'PROFESSIONAL'), 'TEAM_MEMBERS', 'UP_TO_3_PEOPLE', EXTRACT(EPOCH FROM NOW())::INT, EXTRACT(EPOCH FROM NOW())::INT),
  ((SELECT id FROM team_plan WHERE type = 'PROFESSIONAL'), 'FINANCIAL_STATEMENTS', 'AUTO_UPDATED', EXTRACT(EPOCH FROM NOW())::INT, EXTRACT(EPOCH FROM NOW())::INT);
