import { SortBy, SortOrder } from '@/constants/sort';

export const DEFAULT_SORT_OPTIONS = [{ sortBy: SortBy.CREATED_AT, sortOrder: SortOrder.DESC }];

// Info: (20250418 - Liz) 申報頻率
export enum FILING_FREQUENCY {
  BIMONTHLY_FILING = 'BIMONTHLY_FILING',
  MONTHLY_FILING = 'MONTHLY_FILING',
}

export const FILING_FREQUENCY_OPTIONS = [
  { label: FILING_FREQUENCY.BIMONTHLY_FILING, subLabel: 'EVERY_TWO_MONTHS' },
  { label: FILING_FREQUENCY.MONTHLY_FILING, subLabel: 'EVERY_MONTH' },
];

// Info: (20250418 - Liz) 申報方式
export enum FILING_METHOD {
  SINGLE_ENTITY_FILING = 'SINGLE_ENTITY_FILING',
  CONSOLIDATED_FILING = 'CONSOLIDATED_FILING',
  INDIVIDUAL_FILING = 'INDIVIDUAL_FILING',
}

export const FILING_METHOD_OPTIONS = [
  {
    label: FILING_METHOD.SINGLE_ENTITY_FILING,
    subLabel: 'SINGLE_HEAD_OFFICE_WITHOUT_BRANCH_UNITS',
  },
  { label: FILING_METHOD.CONSOLIDATED_FILING, subLabel: 'HEAD_OFFICE_FILES_FOR_ALL_BRANCHES' },
  { label: FILING_METHOD.INDIVIDUAL_FILING, subLabel: 'EACH_UNIT_FILES_SEPARATELY' },
];

// Info: (20250418 - Liz) 申報方式
export enum DECLARANT_FILING_METHOD {
  SELF_FILING = 'SELF_FILING',
  AGENT_FILING = 'AGENT_FILING',
}
