// Info: (20260520 - Tzuhan) Global Semantic Tags for Vendor Rules
export const UniversalAccountTag = {
  TELECOM_EXPENSE: "TELECOM_EXPENSE", // 電信/網路費
  SHIPPING_EXPENSE: "SHIPPING_EXPENSE", // 運費/物流費
  ADVERTISING_EXPENSE: "ADVERTISING_EXPENSE", // 廣告/行銷費
  SOFTWARE_SUBSCRIPTION: "SOFTWARE_SUBSCRIPTION", // 軟體訂閱/雲端服務
  MEAL_EXPENSE: "MEAL_EXPENSE", // 伙食/餐飲費
  OFFICE_SUPPLIES: "OFFICE_SUPPLIES", // 文具/辦公用品
  RENT_EXPENSE: "RENT_EXPENSE", // 租金
  TRANSPORTATION_EXPENSE: "TRANSPORTATION_EXPENSE", // 交通/計程車費
  OTHER_PAYABLES: "OTHER_PAYABLES", // 其他應付款
  CASH_IN_BANK: "CASH_IN_BANK",
  UTILITIES_EXPENSE: "UTILITIES_EXPENSE",
  MISCELLANEOUS_EXPENSE: "MISCELLANEOUS_EXPENSE",
} as const;
