// Info: (20260520 - Tzuhan) Global Semantic Tags for Vendor Rules
export enum UniversalAccountTag {
  CASH = "CASH",
  CASH_IN_BANK = "CASH_IN_BANK",
  ACCOUNTS_RECEIVABLE = "ACCOUNTS_RECEIVABLE",
  ACCOUNTS_PAYABLE = "ACCOUNTS_PAYABLE",
  OTHER_PAYABLES = "OTHER_PAYABLES",
  ACCRUED_RENT = "ACCRUED_RENT",
  REFUNDABLE_DEPOSITS = "REFUNDABLE_DEPOSITS",
  PREPAID_RENT = "PREPAID_RENT",
  PREPAID_EXPENSE = "PREPAID_EXPENSE",
  REVENUE = "REVENUE",
  EXPENSE = "EXPENSE",

  // Info: (20260520 - Tzuhan) Specific expense tags
  TELECOM_EXPENSE = "TELECOM_EXPENSE",
  SHIPPING_EXPENSE = "SHIPPING_EXPENSE",
  UTILITIES_EXPENSE = "UTILITIES_EXPENSE",
  TRAVEL_EXPENSE = "TRAVEL_EXPENSE",
  MARKETING_EXPENSE = "MARKETING_EXPENSE",
  SOFTWARE_EXPENSE = "SOFTWARE_EXPENSE",
  OFFICE_SUPPLIES = "OFFICE_SUPPLIES",
  RENT_EXPENSE = "RENT_EXPENSE",
  ENTERTAINMENT_EXPENSE = "ENTERTAINMENT_EXPENSE",
  MISCELLANEOUS_EXPENSE = "MISCELLANEOUS_EXPENSE",
}
