// Info: (20240416 - Murky) this file contains the interfaces, type guards, type cleaner for OCR and Voucher LLM recognition
// Info: (20240416 - Murky) type
export enum ProgressStatus {
  SUCCESS = 'success',
  FAILED = 'failed',
  IN_PROGRESS = 'inProgress',
  NOT_FOUND = 'notFound',
  ALREADY_UPLOAD = 'alreadyUpload',
  INVALID_INPUT = 'invalidInput',
  LLM_ERROR = 'llmError',
  SYSTEM_ERROR = 'systemError',
  PAUSED = 'paused',
  HAS_BEEN_USED = 'hasBeenUsed',
  WAITING_FOR_UPLOAD = 'waitingForUpload',
}

export enum EventType {
  PAYMENT = 'payment',
  INCOME = 'income',
  TRANSFER = 'transfer',
}

export enum AccountType {
  ASSET = 'asset',
  LIABILITY = 'liability',
  EQUITY = 'equity',
  REVENUE = 'revenue',
  COST = 'cost',
  INCOME = 'income',
  EXPENSE = 'expense',
  GAIN_OR_LOSS = 'gainOrLoss',
  OTHER_COMPREHENSIVE_INCOME = 'otherComprehensiveIncome',
  CASH_FLOW = 'cashFlow',
  //  CHANGE_IN_EQUITY = 'changeInEquity', // ToDo: (20240802 - Julian) [Beta] change in equity statement is not released yet
  OTHER = 'other',
}

export enum VoucherType {
  RECEIVE = 'receive',
  EXPENSE = 'expense',
  TRANSFER = 'transfer',
}

export enum PaymentStatusType {
  PAID = 'paid',
  UNPAID = 'unpaid',
  PARTIAL = 'partial',
}

export enum PaymentPeriodType {
  AT_ONCE = 'atOnce',
  INSTALLMENT = 'installment',
}

export enum AccountSystem {
  IFRS = 'IFRS',
  US_GAAP = 'US_GAAP',
}

export enum EquityType {
  STOCK = 'stock',
  CAPITAL_SURPLUS = 'capitalSurplus',
  RETAINED_EARNINGS = 'retainedEarnings',
  OTHER_EQUITY = 'otherEquity',
}

export const EVENT_TYPE_TO_VOUCHER_TYPE_MAP: {
  [key in EventType]: VoucherType;
} = {
  [EventType.INCOME]: VoucherType.RECEIVE,
  [EventType.PAYMENT]: VoucherType.EXPENSE,
  [EventType.TRANSFER]: VoucherType.TRANSFER,
};

export const MISSING_CODE_MARKERS = ['!', '@', '#', '$', '%'];

export const EVENT_TYPE = {
  ...EventType,
};

export const EQUITY_TYPE_TO_CODE_MAP: {
  [key in EquityType]: string[];
} = {
  [EquityType.STOCK]: ['3110', '3120', '3130', '3140', '3150', '3160', '3170', '3100'],
  [EquityType.CAPITAL_SURPLUS]: [
    '3210',
    '3211',
    '3212',
    '3213',
    '3220',
    '3225',
    '3230',
    '3235',
    '3240',
    '3250',
    '3251',
    '3252',
    '3260',
    '3265',
    '3270',
    '3271',
    '3272',
    '3273',
    '3280',
    '3200',
  ],
  [EquityType.RETAINED_EARNINGS]: ['3310', '3320', '3350', '3351', '3352', '3353', '3220'],
  [EquityType.OTHER_EQUITY]: [
    '3410',
    '3411',
    '341A',
    '3412',
    '341B',
    '3413',
    '341C',
    '3420',
    '3421',
    '3422',
    '3423',
    '3424',
    '342A',
    '342B',
    '342C',
    '342D',
    '342E',
    '3440',
    '3441',
    '3442',
    '3443',
    '3445',
    '3446',
    '3447',
    '3448',
    '3450',
    '3451',
    '345A',
    '345B',
    '345C',
    '345D',
    '345E',
    '345F',
    '345G',
    '345H',
    '3452',
    '345I',
    '345J',
    '345K',
    '345L',
    '345M',
    '345N',
    '345O',
    '345P',
    '3453',
    '345Q',
    '345R',
    '345S',
    '345T',
    '345U',
    '345V',
    '345W',
    '345X',
    '3460',
    '3461',
    '3462',
    '3463',
    '3470',
    '3471',
    '3472',
    '3473',
    '3480',
    '3481',
    '3482',
    '3483',
    '3490',
    '3491',
    '3499',
    '3400',
    '3500',
    '35XX',
    '355X',
    '3XXX',
  ],
};

export const CURRENT_ASSET_CODE = [
  '1100',
  '1110',
  '1120',
  '1136',
  '1139',
  '1140',
  '1150',
  '1160',
  '1170',
  '1180',
  '1190',
  '1195',
  '1196',
  '1197',
  '1198',
  '1199',
  '1200',
  '1210',
  '1220',
  '130X',
  '1400',
  '1410',
  '1450',
  '1460',
  '1470',
];

export const NON_CURRENT_ASSET_CODE = [
  '1510',
  '1517',
  '1535',
  '1538',
  '1560',
  '1550',
  '1600',
  '1750',
  '1755',
  '1760',
  '1780',
  '1830',
  '1840',
  '1900',
];

export const ASSET_CODE = [...CURRENT_ASSET_CODE, ...NON_CURRENT_ASSET_CODE];

/**
 * A collection of special accounts with detailed properties.
 *
 * @type {Object.<string, {
 *   system: string,
 *   type: AccountType,
 *   debit: boolean,
 *   liquidity: boolean,
 *   code: string,
 *   name: string,
 *   forUser: boolean,
 *   parentCode: string,
 *   rootCode: string,
 *   level: number
 * }>}
 *
 * @property {string} system - The system to which the account belongs.
 * @property {AccountType} type - The type of the account.
 * @property {boolean} debit - Indicates if the account is a debit account.
 * @property {boolean} liquidity - Indicates if the account is a liquidity account.
 * @property {string} code - The code of the account.
 * @property {string} name - The name of the account.
 * @property {boolean} forUser - Indicates if the account is for user purposes.
 * @property {string} parentCode - The parent code of the account.
 * @property {string} rootCode - The root code of the account.
 * @property {number} level - The hierarchical level of the account.
 */
export const SPECIAL_ACCOUNTS: {
  [key: string]: {
    system: string;
    type: AccountType;
    debit: boolean;
    liquidity: boolean;
    code: string;
    name: string;
    forUser: boolean;
    parentCode: string;
    rootCode: string;
    level: number;
  };
} = {
  NET_INCOME: {
    system: 'IFRS',
    type: AccountType.INCOME,
    debit: true,
    liquidity: true,
    code: '8200',
    name: '本期淨利（淨損）',
    forUser: false,
    parentCode: '8200',
    rootCode: '8200',
    level: 0,
  },
  OTHER_COMPREHENSIVE_INCOME: {
    system: 'IFRS',
    type: AccountType.OTHER_COMPREHENSIVE_INCOME,
    debit: false,
    liquidity: true,
    code: '8300',
    name: '其他綜合損益(淨額)',
    forUser: false,
    parentCode: '8300',
    rootCode: '8300',
    level: 0,
  },
  NET_INCOME_IN_EQUITY: {
    system: 'IFRS',
    type: AccountType.EQUITY,
    debit: false,
    liquidity: false,
    code: '3353',
    name: '本期損益',
    forUser: true,
    parentCode: '3350',
    rootCode: '3350',
    level: 3,
  },
  ACCUMULATED_PROFIT_AND_LOSS: {
    system: 'IFRS',
    type: AccountType.EQUITY,
    debit: false,
    liquidity: false,
    code: '3351',
    name: '累積盈虧',
    forUser: true,
    parentCode: '3350',
    rootCode: '3350',
    level: 3,
  },
  OTHER_EQUITY_OTHER: {
    system: 'IFRS',
    type: AccountType.EQUITY,
    debit: false,
    liquidity: false,
    code: '3499',
    name: '其他權益－其他',
    forUser: false,
    parentCode: '3490',
    rootCode: '3400',
    level: 3,
  },
  ASSET_TOTAL: {
    system: 'IFRS',
    type: AccountType.ASSET,
    debit: true,
    liquidity: true,
    code: '1XXX',
    name: '資產',
    forUser: false,
    parentCode: '1XXX',
    rootCode: '1XXX',
    level: 0,
  },
  LIABILITY_TOTAL: {
    system: 'IFRS',
    type: AccountType.LIABILITY,
    debit: false,
    liquidity: true,
    code: '2XXX',
    name: '負債',
    forUser: false,
    parentCode: '2XXX',
    rootCode: '2XXX',
    level: 0,
  },
  EQUITY_TOTAL: {
    system: 'IFRS',
    type: AccountType.EQUITY,
    debit: false,
    liquidity: false,
    code: '3XXX',
    name: '權益',
    forUser: false,
    parentCode: '3XXX',
    rootCode: '3XXX',
    level: 0,
  },
  FIXED_ASSET: {
    system: 'IFRS',
    type: AccountType.ASSET,
    debit: true,
    liquidity: false,
    code: '1600',
    name: '不動產、廠房及設備',
    forUser: false,
    parentCode: '15XX',
    rootCode: '1600',
    level: 2,
  },
  LIABILITY_AND_EQUITY_TOTAL: {
    system: 'IFRS',
    type: AccountType.LIABILITY,
    debit: false,
    liquidity: true,
    code: '3X2X',
    name: '負債及權益總計',
    forUser: false,
    parentCode: '3X2X',
    rootCode: '3X2X',
    level: 0,
  },
  OPERATING_INCOME: {
    system: 'IFRS',
    type: AccountType.REVENUE,
    debit: false,
    liquidity: true,
    code: '4000',
    name: '營業收入',
    forUser: false,
    parentCode: '4000',
    rootCode: '4000',
    level: 0,
  },
  OPERATING_COST: {
    system: 'IFRS',
    type: AccountType.COST,
    debit: true,
    liquidity: true,
    code: '5000',
    name: '營業成本',
    forUser: false,
    parentCode: '5000',
    rootCode: '5000',
    level: 0,
  },
  SELLING_EXPENSE_TOTAL: {
    system: 'IFRS',
    type: AccountType.EXPENSE,
    debit: true,
    liquidity: true,
    code: '6100',
    name: '推銷費用',
    forUser: false,
    parentCode: '6000',
    rootCode: '6100',
    level: 1,
  },
  OPERATING_EXPENSE_TOTAL: {
    system: 'IFRS',
    type: AccountType.EXPENSE,
    debit: true,
    liquidity: true,
    code: '6200',
    name: '管理費用',
    forUser: false,
    parentCode: '6000',
    rootCode: '6200',
    level: 1,
  },
  RD_EXPENSE_TOTAL: {
    system: 'IFRS',
    type: AccountType.EXPENSE,
    debit: true,
    liquidity: true,
    code: '6300',
    name: '研究發展費用',
    forUser: false,
    parentCode: '6000',
    rootCode: '6300',
    level: 1,
  },
  INVENTORY_TOTAL: {
    system: 'IFRS',
    type: AccountType.ASSET,
    debit: true,
    liquidity: true,
    code: '130X',
    name: '存貨',
    forUser: false,
    parentCode: '11XX',
    rootCode: '130X',
    level: 2,
  },
  CASH_GENERATE_FROM_OPERATING: {
    system: 'IFRS',
    type: AccountType.CASH_FLOW,
    debit: false,
    liquidity: true,
    code: 'A33000',
    name: '營運產生之現金流入（流出）',
    forUser: false,
    parentCode: 'AAAA0',
    rootCode: 'A33000',
    level: 1,
  },
  CASH_OUTFLOW_FOR_DIVIDEND: {
    system: 'IFRS',
    type: AccountType.CASH_FLOW,
    debit: false,
    liquidity: true,
    code: 'A33400',
    name: '支付之股利',
    forUser: false,
    parentCode: 'AAAA0',
    rootCode: 'A33400',
    level: 1,
  },
  CASH_FROM_TAX_REFUND: {
    system: 'IFRS',
    type: AccountType.CASH_FLOW,
    debit: false,
    liquidity: true,
    code: 'A33500',
    name: '退還（支付）之所得稅',
    forUser: false,
    parentCode: 'AAAA0',
    rootCode: 'A33500',
    level: 1,
  },
  CASH_FLOW_FROM_OPERATING: {
    system: 'IFRS',
    type: AccountType.CASH_FLOW,
    debit: false,
    liquidity: true,
    code: 'AAAA',
    name: '營業活動之淨現金流入（流出）',
    forUser: false,
    parentCode: 'AAAA',
    rootCode: 'AAAA',
    level: 0,
  },
  /**
   * Info: (20241017 - Murky)
   * @description this is for marking special account, not rear account
   */
  CASH_FLOW_FROM_OPERATING_SPECIAL_ACCOUNT: {
    system: 'IFRS',
    type: AccountType.CASH_FLOW,
    debit: false,
    liquidity: true,
    code: '$$$$',
    name: '特殊營業活動之淨現金流入（流出）',
    forUser: false,
    parentCode: '$$$$',
    rootCode: '$$$$',
    level: 0,
  },
  CASH_FLOW_FROM_INVESTING: {
    system: 'IFRS',
    type: AccountType.CASH_FLOW,
    debit: false,
    liquidity: true,
    code: 'BBBB',
    name: '投資活動之現金流量',
    forUser: false,
    parentCode: 'BBBB',
    rootCode: 'BBBB',
    level: 0,
  },
  CASH_FLOW_FROM_FINANCING: {
    system: 'IFRS',
    type: AccountType.CASH_FLOW,
    debit: false,
    liquidity: true,
    code: 'CCCC',
    name: '籌資活動之現金流量',
    forUser: false,
    parentCode: 'CCCC',
    rootCode: 'CCCC',
    level: 0,
  },
  CASH_FLOW_FROM_FOREIGN_EXCHANGE: {
    system: 'IFRS',
    type: AccountType.CASH_FLOW,
    debit: false,
    liquidity: true,
    code: 'DDDD',
    name: '匯率變動對現金及約當現金之影響',
    forUser: false,
    parentCode: 'DDDD',
    rootCode: 'DDDD',
    level: 0,
  },
  CASH_INCREASE_THIS_PERIOD: {
    system: 'IFRS',
    type: AccountType.CASH_FLOW,
    debit: false,
    liquidity: true,
    code: 'EEEE',
    name: '本期現金及約當現金增加（減少）數',
    forUser: false,
    parentCode: 'EEEE',
    rootCode: 'EEEE',
    level: 0,
  },
  CASH_AMOUNT_IN_BEGINNING: {
    system: 'IFRS',
    type: AccountType.CASH_FLOW,
    debit: false,
    liquidity: true,
    code: 'E00100',
    name: '期初現金及約當現金餘額',
    forUser: false,
    parentCode: 'E00100',
    rootCode: 'E00100',
    level: 0,
  },
  CASH_AMOUNT_IN_END: {
    system: 'IFRS',
    type: AccountType.CASH_FLOW,
    debit: false,
    liquidity: true,
    code: 'E00200',
    name: '期末現金及約當現金餘額',
    forUser: false,
    parentCode: 'E00200',
    rootCode: 'E00200',
    level: 0,
  },
  NET_INCOME_IN_CASH_FLOW: {
    system: 'IFRS',
    type: AccountType.CASH_FLOW,
    debit: false,
    liquidity: true,
    code: 'A10000',
    name: '本期稅前淨利（淨損）',
    forUser: false,
    parentCode: 'AAAA0',
    rootCode: 'A10000',
    level: 1,
  },
  SALES_DEPRECIATION: {
    system: 'IFRS',
    type: AccountType.EXPENSE,
    debit: true,
    liquidity: true,
    code: '6124',
    name: '推銷費用 - 折舊',
    forUser: true,
    parentCode: '6100',
    rootCode: '6124',
    level: 2,
  },
  SALES_AMORTIZATION: {
    system: 'IFRS',
    type: AccountType.EXPENSE,
    debit: true,
    liquidity: true,
    code: '6125',
    name: '推銷費用 - 各項攤提',
    forUser: true,
    parentCode: '6100',
    rootCode: '6125',
    level: 2,
  },
  MANAGE_DEPRECIATION: {
    system: 'IFRS',
    type: AccountType.EXPENSE,
    debit: true,
    liquidity: true,
    code: '6224',
    name: '管理費用 - 折舊',
    forUser: true,
    parentCode: '6200',
    rootCode: '6224',
    level: 2,
  },
  MANAGE_AMORTIZATION: {
    system: 'IFRS',
    type: AccountType.EXPENSE,
    debit: true,
    liquidity: true,
    code: '6225',
    name: '管理費用 - 各項攤提',
    forUser: true,
    parentCode: '6200',
    rootCode: '6225',
    level: 2,
  },
  RD_DEPRECIATION: {
    system: 'IFRS',
    type: AccountType.EXPENSE,
    debit: true,
    liquidity: true,
    code: '6324',
    name: '研究發展費用 - 折舊及折耗',
    forUser: true,
    parentCode: '6300',
    rootCode: '6324',
    level: 2,
  },
  CASH_INVEST_PPE: {
    system: 'IFRS',
    type: AccountType.CASH_FLOW,
    debit: false,
    liquidity: true,
    code: 'B02700',
    name: '取得不動產、廠房及設備',
    forUser: false,
    parentCode: 'BBBB',
    rootCode: 'B02700',
    level: 1,
  },
  CASH_DISPOSE_PPE: {
    system: 'IFRS',
    type: AccountType.CASH_FLOW,
    debit: false,
    liquidity: true,
    code: 'B02800',
    name: '處分不動產、廠房及設備',
    forUser: false,
    parentCode: 'BBBB',
    rootCode: 'B02800',
    level: 1,
  },
  CASH_INVEST_FVPL: {
    system: 'IFRS',
    type: AccountType.CASH_FLOW,
    debit: false,
    liquidity: true,
    code: 'B00100',
    name: '取得透過損益按公允價值衡量之金融資產',
    forUser: false,
    parentCode: 'BBBB',
    rootCode: 'B00100',
    level: 1,
  },
  CASH_INVEST_FVOCI: {
    system: 'IFRS',
    type: AccountType.CASH_FLOW,
    debit: false,
    liquidity: true,
    code: 'B00010',
    name: '取得透過其他綜合損益按公允價值衡量之金融資產',
    forUser: false,
    parentCode: 'BBBB',
    rootCode: 'B00010',
    level: 1,
  },
  CASH_DISPOSE_FVOCI: {
    system: 'IFRS',
    type: AccountType.CASH_FLOW,
    debit: false,
    liquidity: true,
    code: 'B00020',
    name: '處分透過其他綜合損益按公允價值衡量之金融資產',
    forUser: false,
    parentCode: 'BBBB',
    rootCode: 'B00020',
    level: 1,
  },
  CASH_INVEST_AMORTIZED_FINANCIAL_ASSET: {
    system: 'IFRS',
    type: AccountType.CASH_FLOW,
    debit: false,
    liquidity: true,
    code: 'B00040',
    name: '取得按攤銷後成本衡量之金融資產',
    forUser: false,
    parentCode: 'BBBB',
    rootCode: 'B00040',
    level: 1,
  },
  CASH_DISPOSE_AMORTIZED_FINANCIAL_ASSET: {
    system: 'IFRS',
    type: AccountType.CASH_FLOW,
    debit: false,
    liquidity: true,
    code: 'B00050',
    name: '處分按攤銷後成本衡量之金融資產',
    forUser: false,
    parentCode: 'BBBB',
    rootCode: 'B00050',
    level: 1,
  },
  CASH_REMOVE_HEDGE_ASSET: {
    system: 'IFRS',
    type: AccountType.CASH_FLOW,
    debit: false,
    liquidity: true,
    code: 'B01700',
    name: '除列避險之金融負債',
    forUser: false,
    parentCode: 'BBBB',
    rootCode: 'B01700',
    level: 1,
  },
  CASH_RECEIVE_STOCK_DIVIDEND: {
    system: 'IFRS',
    type: AccountType.CASH_FLOW,
    debit: false,
    liquidity: true,
    code: 'B07600',
    name: '收取之股利',
    forUser: false,
    parentCode: 'BBBB',
    rootCode: 'B07600',
    level: 1,
  },
  CASH_INVEST_INTANGIBLE_ASSET: {
    system: 'IFRS',
    type: AccountType.CASH_FLOW,
    debit: false,
    liquidity: true,
    code: 'B04500',
    name: '取得無形資產',
    forUser: false,
    parentCode: 'BBBB',
    rootCode: 'B04500',
    level: 1,
  },
  CASH_DISPOSE_INTANGIBLE_ASSET: {
    system: 'IFRS',
    type: AccountType.CASH_FLOW,
    debit: false,
    liquidity: true,
    code: 'B04600',
    name: '處分無形資產',
    forUser: false,
    parentCode: 'BBBB',
    rootCode: 'B04600',
    level: 1,
  },
  INPUT_TAX: {
    system: 'IFRS',
    type: AccountType.COST,
    debit: true,
    liquidity: true,
    code: '1423',
    name: '進項稅額',
    forUser: true,
    parentCode: '1410',
    rootCode: '1410',
    level: 3,
  },
  OUTPUT_TAX: {
    system: 'IFRS',
    type: AccountType.LIABILITY,
    debit: false,
    liquidity: true,
    code: '2214',
    name: '銷項稅額',
    forUser: true,
    parentCode: '2200',
    rootCode: '2200',
    level: 3,
  },
  ACCOUNT_PAYABLE: {
    system: 'IFRS',
    type: AccountType.LIABILITY,
    debit: false,
    liquidity: true,
    code: '2171',
    name: '應付帳款',
    forUser: true,
    parentCode: '2170',
    rootCode: '2170',
    level: 3,
  },
};
