export const ANALYSIS_CATEGORY = {
  BALANCE_SHEET: "BALANCE_SHEET",
  CASH_FLOW: "CASH_FLOW",
  INCOME_STATEMENT: "INCOME_STATEMENT",
  FINANCIAL_COMPLIANCE: "FINANCIAL_COMPLIANCE",
  FINANCIAL_HEALTH: "FINANCIAL_HEALTH",
  IRSC: "IRSC",
  CARBON_HEALTH_CHECK: "CARBON_HEALTH_CHECK",
  NET_ZERO_EMISSIONS: "NET_ZERO_EMISSIONS",
  MARKET_TRENDS: "MARKET_TRENDS",
  INDUSTRY_DEVELOPMENT: "INDUSTRY_DEVELOPMENT",
  FINANCIAL_PRODUCT_RATING: "FINANCIAL_PRODUCT_RATING",
  AI_CONSULTING: "AI_CONSULTING",
  CERTIFICATE_ANALYSIS: "CERTIFICATE_ANALYSIS",
  TRANSPORTATION_CARBON_FOOTPRINT: "TRANSPORTATION_CARBON_FOOTPRINT",
} as const;

export type AnalysisCategory =
  (typeof ANALYSIS_CATEGORY)[keyof typeof ANALYSIS_CATEGORY];

export const ANALYSIS_PERIOD = {
  DAILY: "DAILY",
  WEEKLY: "WEEKLY",
  MONTHLY: "MONTHLY",
  SEASONLY: "SEASONLY",
  YEARLY: "YEARLY",
} as const;

export type AnalysisPeriod =
  (typeof ANALYSIS_PERIOD)[keyof typeof ANALYSIS_PERIOD];

export const INTERNAL_CATEGORIES = [
  ANALYSIS_CATEGORY.BALANCE_SHEET,
  ANALYSIS_CATEGORY.CASH_FLOW,
  ANALYSIS_CATEGORY.INCOME_STATEMENT,
  ANALYSIS_CATEGORY.IRSC,
  ANALYSIS_CATEGORY.FINANCIAL_COMPLIANCE,
  ANALYSIS_CATEGORY.FINANCIAL_HEALTH,
  ANALYSIS_CATEGORY.CARBON_HEALTH_CHECK,
  ANALYSIS_CATEGORY.NET_ZERO_EMISSIONS,
] as const;

export const EXTERNAL_CATEGORIES = [
  ANALYSIS_CATEGORY.MARKET_TRENDS,
  ANALYSIS_CATEGORY.INDUSTRY_DEVELOPMENT,
  ANALYSIS_CATEGORY.IRSC,
  ANALYSIS_CATEGORY.FINANCIAL_PRODUCT_RATING,
  ANALYSIS_CATEGORY.CARBON_HEALTH_CHECK,
  ANALYSIS_CATEGORY.NET_ZERO_EMISSIONS,
] as const;

export const COUNTRIES = ["tw", "us", "cn", "jp", "kr", "eu"] as const;

export const CATEGORIES = [
  ...INTERNAL_CATEGORIES,
  ...EXTERNAL_CATEGORIES,
] as const;

export const PERIOD_TYPES = [
  ANALYSIS_PERIOD.YEARLY,
  ANALYSIS_PERIOD.SEASONLY,
  ANALYSIS_PERIOD.MONTHLY,
  ANALYSIS_PERIOD.WEEKLY,
  ANALYSIS_PERIOD.DAILY,
] as const;

export const ROUTE_MODE = {
  LAND: "LAND",
  SEA_LAND: "SEA_LAND",
  AIR_LAND: "AIR_LAND",
  SEA_LAND_AIR: "SEA_LAND_AIR",
} as const;

export type RouteMode = (typeof ROUTE_MODE)[keyof typeof ROUTE_MODE];

export const MILEAGE_ACTION = {
  PARSE_MULTIPLE: "parse_multiple",
  CALCULATE_BATCH: "calculate_batch",
} as const;

export type MileageAction =
  (typeof MILEAGE_ACTION)[keyof typeof MILEAGE_ACTION];
