import { IAPIConfig, IAPIName } from '@/interfaces/api_connection';

const apiVersion = 'v1';
const apiPrefix = `/api/${apiVersion}`;

export enum HttpMethod {
  GET = 'GET',
  POST = 'POST',
  PUT = 'PUT',
  DELETE = 'DELETE',
  PATCH = 'PATCH',
  HEAD = 'HEAD',
}

export enum APIName {
  SIGN_UP = 'SIGN_UP',
  SIGN_IN = 'SIGN_IN',
  SIGN_OUT = 'SIGN_OUT',
  EMAIL = 'EMAIL',
  USER_GET_BY_ID = 'USER_GET_BY_ID',
  USER_UPDATE = 'USER_UPDATE',
  COMPANY_LIST = 'COMPANY_LIST',
  COMPANY_ADD = 'COMPANY_ADD',
  COMPANY_ADD_BY_INVITATION_CODE = 'COMPANY_ADD_BY_INVITATION_CODE',
  PROFIT_GET_INSIGHT = 'PROFIT_GET_INSIGHT',
  PROFIT_GET_TREND_IN_PERIOD = 'PROFIT_GET_TREND_IN_PERIOD',
  PROFIT_GET_MARGIN_TREND_IN_PERIOD = 'PROFIT_GET_MARGIN_TREND_IN_PERIOD',
  PROJECT_LIST_PROGRESS = 'PROJECT_LIST_PROGRESS',
  PROJECT_LIST_PROFIT_COMPARISON = 'PROJECT_LIST_PROFIT_COMPARISON',
  INVOCIE_UPLOAD = 'INVOCIE_UPLOAD',
  INVOCIE_LIST_UNBOUNDED = 'INVOCIE_LIST_UNBOUNDED',
  INVOCIE_GET_BY_ID = 'INVOCIE_GET_BY_ID',
  ASSET_MANAGEMENT_LIST = 'ASSET_MANAGEMENT_LIST',
  ASSET_MANAGEMENT_ADD = 'ASSET_MANAGEMENT_ADD',
  ASSET_MANAGEMENT_GET_BY_ID = 'ASSET_MANAGEMENT_GET_BY_ID',
  ASSET_MANAGEMENT_UPDATE = 'ASSET_MANAGEMENT_UPDATE',
  JOURNAL_GENERATE = 'JOURNAL_GENERATE',
  JOURNAL_GET_PROGRESS_STATUS = 'JOURNAL_GET_PROGRESS_STATUS',
  JOURNAL_GET_PREVIEW_BY_ID = 'JOURNAL_GET_PREVIEW_BY_ID',
  JOURNAL_UPDATE = 'JOURNAL_UPDATE',
  JOURNAL_DELETE = 'JOURNAL_DELETE',
  JOURNAL_LIST_PROGRESS_STATUS = 'JOURNAL_LIST_PROGRESS_STATUS',
  JOURNAL_LIST = 'JOURNAL_LIST',
  JOURNAL_GET_BY_ID = 'JOURNAL_GET_BY_ID',
  VOUCHER_GENERATE = 'VOUCHER_GENERATE',
  VOUCHER_LIST = 'VOUCHER_LIST',
  FINANCIAL_REPORT_LIST_PROGRESS_STATUS = 'FINANCIAL_REPORT_LIST_PROGRESS_STATUS',
  FINANCIAL_REPORT_LIST = 'FINANCIAL_REPORT_LIST',
  FINANCIAL_REPORT_GENERATE = 'FINANCIAL_REPORT_GENERATE',
  FINANCIAL_REPORT_GET_BY_ID = 'FINANCIAL_REPORT_GET_BY_ID',
  ANALYSIS_REPORT_LIST_PROGRESS_STATUS = 'ANALYSIS_REPORT_LIST_PROGRESS_STATUS',
  ANALYSIS_REPORT_LIST = 'ANALYSIS_REPORT_LIST',
  ANALYSIS_REPORT_GENERATE = 'ANALYSIS_REPORT_GENERATE',
  ANALYSIS_REPORT_GET_BY_ID = 'ANALYSIS_REPORT_GET_BY_ID',
}

export enum APIPath {
  SIGN_UP = `${apiPrefix}/sign-up`,
  SIGN_IN = `${apiPrefix}/sign-in`,
  SIGN_OUT = `${apiPrefix}/sign-out`,
  EMAIL = `${apiPrefix}/email`,
  USER_GET_BY_ID = `${apiPrefix}/user/:userId`,
  USER_UPDATE = `${apiPrefix}/user/:userId`,
  COMPANY_LIST = `${apiPrefix}/company`,
  COMPANY_ADD = `${apiPrefix}/company`,
  COMPANY_ADD_BY_INVITATION_CODE = `${apiPrefix}/company/invitation_code`,
  PROFIT_GET_INSIGHT = `${apiPrefix}/company/:companyId/profit_insight`,
  PROFIT_GET_TREND_IN_PERIOD = `${apiPrefix}/company/:companyId/profit_trend`,
  PROFIT_GET_MARGIN_TREND_IN_PERIOD = `${apiPrefix}/company/:companyId/profit_margin_trend`,
  PROJECT_LIST_PROGRESS = `${apiPrefix}/company/:companyId/project_progress`,
  PROJECT_LIST_PROFIT_COMPARISON = `${apiPrefix}/company/:companyId/project_profit_comparison`,
  INVOCIE_UPLOAD = `${apiPrefix}/company/:companyId/invoice`,
  INVOCIE_LIST_UNBOUNDED = `${apiPrefix}/company/:companyId/invoice_unbounded`,
  INVOCIE_GET_BY_ID = `${apiPrefix}/company/:companyId/invoice/:invoiceId`,
  ASSET_MANAGEMENT_LIST = `${apiPrefix}/company/:companyId/asset_management`,
  ASSET_MANAGEMENT_ADD = `${apiPrefix}/company/:companyId/asset_management`,
  ASSET_MANAGEMENT_GET_BY_ID = `${apiPrefix}/company/:companyId/asset_management/:assetId`,
  ASSET_MANAGEMENT_UPDATE = `${apiPrefix}/company/:companyId/asset_management/:assetId`,
  JOURNAL_GENERATE = `${apiPrefix}/company/:companyId/voucher`,
  JOURNAL_GET_PROGRESS_STATUS = `${apiPrefix}/company/:companyId/voucher/:voucherId/status`,
  JOURNAL_GET_PREVIEW_BY_ID = `${apiPrefix}/company/:companyId/voucher/:voucherId`,
  JOURNAL_UPDATE = `${apiPrefix}/company/:companyId/voucher/:voucherId`,
  JOURNAL_DELETE = `${apiPrefix}/company/:companyId/voucher/:voucherId`,
  JOURNAL_LIST_PROGRESS_STATUS = `${apiPrefix}/company/:companyId/voucher_status`,
  JOURNAL_LIST = `${apiPrefix}/company/:companyId/voucher`,
  JOURNAL_GET_BY_ID = `${apiPrefix}/company/:companyId/journal/:journalId`,
  VOUCHER_GENERATE = `${apiPrefix}/company/:companyId/journal`,
  VOUCHER_LIST = `${apiPrefix}/company/:companyId/journal`,
  FINANCIAL_REPORT_LIST_PROGRESS_STATUS = `${apiPrefix}/company/:companyId/report_financial_status`,
  FINANCIAL_REPORT_LIST = `${apiPrefix}/company/:companyId/report_financial`,
  FINANCIAL_REPORT_GENERATE = `${apiPrefix}/company/:companyId/report_financial`,
  FINANCIAL_REPORT_GET_BY_ID = `${apiPrefix}/company/:companyId/report_financial/:reportId`,
  ANALYSIS_REPORT_LIST_PROGRESS_STATUS = `${apiPrefix}/company/:companyId/report_analysis_status`,
  ANALYSIS_REPORT_LIST = `${apiPrefix}/company/:companyId/report_analysis`,
  ANALYSIS_REPORT_GENERATE = `${apiPrefix}/company/:companyId/report_analysis`,
  ANALYSIS_REPORT_GET_BY_ID = `${apiPrefix}/company/:companyId/report_analysis/:reportId`,
}

export const APIConfig: Record<IAPIName, IAPIConfig> = {
  [APIName.SIGN_UP]: {
    name: APIName.SIGN_UP,
    method: HttpMethod.POST,
    path: APIPath.SIGN_UP,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.SIGN_IN]: {
    name: APIName.SIGN_IN,
    method: HttpMethod.POST,
    path: APIPath.SIGN_IN,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.SIGN_OUT]: {
    name: APIName.SIGN_OUT,
    method: HttpMethod.POST,
    path: APIPath.SIGN_OUT,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.EMAIL]: {
    name: APIName.EMAIL,
    method: HttpMethod.POST,
    path: APIPath.EMAIL,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.USER_GET_BY_ID]: {
    name: APIName.USER_GET_BY_ID,
    method: HttpMethod.GET,
    path: APIPath.USER_GET_BY_ID,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.INVOCIE_GET_BY_ID]: {
    name: APIName.INVOCIE_GET_BY_ID,
    method: HttpMethod.GET,
    path: APIPath.INVOCIE_GET_BY_ID,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.INVOCIE_UPLOAD]: {
    name: APIName.INVOCIE_UPLOAD,
    method: HttpMethod.POST,
    path: APIPath.INVOCIE_UPLOAD,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.FINANCIAL_REPORT_GENERATE]: {
    name: APIName.FINANCIAL_REPORT_GENERATE,
    method: HttpMethod.POST,
    path: APIPath.FINANCIAL_REPORT_GENERATE,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.FINANCIAL_REPORT_LIST_PROGRESS_STATUS]: {
    name: APIName.FINANCIAL_REPORT_LIST_PROGRESS_STATUS,
    method: HttpMethod.GET,
    path: APIPath.FINANCIAL_REPORT_LIST_PROGRESS_STATUS,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.FINANCIAL_REPORT_GET_BY_ID]: {
    name: APIName.FINANCIAL_REPORT_GET_BY_ID,
    method: HttpMethod.GET,
    path: APIPath.FINANCIAL_REPORT_GET_BY_ID,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.ANALYSIS_REPORT_GENERATE]: {
    name: APIName.ANALYSIS_REPORT_GENERATE,
    method: HttpMethod.POST,
    path: APIPath.ANALYSIS_REPORT_GENERATE,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.ANALYSIS_REPORT_LIST_PROGRESS_STATUS]: {
    name: APIName.ANALYSIS_REPORT_LIST_PROGRESS_STATUS,
    method: HttpMethod.GET,
    path: APIPath.ANALYSIS_REPORT_LIST_PROGRESS_STATUS,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.ANALYSIS_REPORT_GET_BY_ID]: {
    name: APIName.ANALYSIS_REPORT_GET_BY_ID,
    method: HttpMethod.GET,
    path: APIPath.ANALYSIS_REPORT_GET_BY_ID,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.VOUCHER_GENERATE]: {
    name: APIName.VOUCHER_GENERATE,
    method: HttpMethod.POST,
    path: APIPath.VOUCHER_GENERATE,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.JOURNAL_GET_PROGRESS_STATUS]: {
    name: APIName.JOURNAL_GET_PROGRESS_STATUS,
    method: HttpMethod.GET,
    path: APIPath.JOURNAL_GET_PROGRESS_STATUS,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.JOURNAL_GET_PREVIEW_BY_ID]: {
    name: APIName.JOURNAL_GET_PREVIEW_BY_ID,
    method: HttpMethod.GET,
    path: APIPath.JOURNAL_GET_PREVIEW_BY_ID,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.VOUCHER_LIST]: {
    name: APIName.VOUCHER_LIST,
    method: HttpMethod.GET,
    path: APIPath.VOUCHER_LIST,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.JOURNAL_GENERATE]: {
    name: APIName.JOURNAL_GENERATE,
    method: HttpMethod.POST,
    path: APIPath.JOURNAL_GENERATE,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.JOURNAL_LIST]: {
    name: APIName.JOURNAL_LIST,
    method: HttpMethod.GET,
    path: APIPath.JOURNAL_LIST,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.JOURNAL_GET_BY_ID]: {
    name: APIName.JOURNAL_GET_BY_ID,
    method: HttpMethod.GET,
    path: APIPath.JOURNAL_GET_BY_ID,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  USER_UPDATE: {
    name: APIName.USER_UPDATE,
    method: HttpMethod.PUT,
    path: APIPath.USER_UPDATE,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  COMPANY_LIST: {
    name: APIName.COMPANY_LIST,
    method: HttpMethod.GET,
    path: APIPath.COMPANY_LIST,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  COMPANY_ADD: {
    name: APIName.COMPANY_ADD,
    method: HttpMethod.POST,
    path: APIPath.COMPANY_ADD,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  COMPANY_ADD_BY_INVITATION_CODE: {
    name: APIName.COMPANY_ADD_BY_INVITATION_CODE,
    method: HttpMethod.POST,
    path: APIPath.COMPANY_ADD_BY_INVITATION_CODE,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  PROFIT_GET_INSIGHT: {
    name: APIName.PROFIT_GET_INSIGHT,
    method: HttpMethod.GET,
    path: APIPath.PROFIT_GET_INSIGHT,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  PROFIT_GET_TREND_IN_PERIOD: {
    name: APIName.PROFIT_GET_TREND_IN_PERIOD,
    method: HttpMethod.GET,
    path: APIPath.PROFIT_GET_TREND_IN_PERIOD,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  PROFIT_GET_MARGIN_TREND_IN_PERIOD: {
    name: APIName.PROFIT_GET_MARGIN_TREND_IN_PERIOD,
    method: HttpMethod.GET,
    path: APIPath.PROFIT_GET_MARGIN_TREND_IN_PERIOD,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  PROJECT_LIST_PROGRESS: {
    name: APIName.PROJECT_LIST_PROGRESS,
    method: HttpMethod.GET,
    path: APIPath.PROJECT_LIST_PROGRESS,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  PROJECT_LIST_PROFIT_COMPARISON: {
    name: APIName.PROJECT_LIST_PROFIT_COMPARISON,
    method: HttpMethod.GET,
    path: APIPath.PROJECT_LIST_PROFIT_COMPARISON,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  INVOCIE_LIST_UNBOUNDED: {
    name: APIName.INVOCIE_LIST_UNBOUNDED,
    method: HttpMethod.GET,
    path: APIPath.INVOCIE_LIST_UNBOUNDED,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  ASSET_MANAGEMENT_LIST: {
    name: APIName.ASSET_MANAGEMENT_LIST,
    method: HttpMethod.GET,
    path: APIPath.ASSET_MANAGEMENT_LIST,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  ASSET_MANAGEMENT_ADD: {
    name: APIName.ASSET_MANAGEMENT_ADD,
    method: HttpMethod.POST,
    path: APIPath.ASSET_MANAGEMENT_ADD,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  ASSET_MANAGEMENT_GET_BY_ID: {
    name: APIName.ASSET_MANAGEMENT_GET_BY_ID,
    method: HttpMethod.GET,
    path: APIPath.ASSET_MANAGEMENT_GET_BY_ID,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  ASSET_MANAGEMENT_UPDATE: {
    name: APIName.ASSET_MANAGEMENT_UPDATE,
    method: HttpMethod.PUT,
    path: APIPath.ASSET_MANAGEMENT_UPDATE,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  JOURNAL_UPDATE: {
    name: APIName.JOURNAL_UPDATE,
    method: HttpMethod.PUT,
    path: APIPath.JOURNAL_UPDATE,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  JOURNAL_DELETE: {
    name: APIName.JOURNAL_DELETE,
    method: HttpMethod.DELETE,
    path: APIPath.JOURNAL_DELETE,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  JOURNAL_LIST_PROGRESS_STATUS: {
    name: APIName.JOURNAL_LIST_PROGRESS_STATUS,
    method: HttpMethod.GET,
    path: APIPath.JOURNAL_LIST_PROGRESS_STATUS,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  FINANCIAL_REPORT_LIST: {
    name: APIName.FINANCIAL_REPORT_LIST,
    method: HttpMethod.GET,
    path: APIPath.FINANCIAL_REPORT_LIST,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  ANALYSIS_REPORT_LIST: {
    name: APIName.ANALYSIS_REPORT_LIST,
    method: HttpMethod.GET,
    path: APIPath.ANALYSIS_REPORT_LIST,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
};
