import { IAPIConfig, IAPIName } from '@/interfaces/api_connection';

const apiVersion = 'v1';
const apiPrefix = `/api/${apiVersion}`;

export enum HttpMethod {
  GET = 'GET',
  POST = 'POST',
  PUT = 'PUT',
  DELETE = 'DELETE',
  PATCH = 'PATCH',
  HEAD = 'HEAD',
}

export enum APIName {
  SIGN_UP = 'SIGN_UP',
  SIGN_IN = 'SIGN_IN',
  SIGN_OUT = 'SIGN_OUT',
  EMAIL = 'EMAIL',
  USER_GET_BY_ID = 'USER_GET_BY_ID',
  USER_UPDATE = 'USER_UPDATE',
  COMPANY_LIST = 'COMPANY_LIST',
  COMPANY_ADD = 'COMPANY_ADD',
  COMPANY_ADD_BY_INVITATION_CODE = 'COMPANY_ADD_BY_INVITATION_CODE',
  COMPANY_SELECT = 'COMPANY_SELECT',
  PROFIT_GET_INSIGHT = 'PROFIT_GET_INSIGHT',
  INCOME_EXPENSE_GET_TREND_IN_PERIOD = 'INCOME_EXPENSE_GET_TREND_IN_PERIOD',
  LABOR_COST_CHART = 'LABOR_COST_CHART',
  PROFIT_GET_TREND_IN_PERIOD = 'PROFIT_GET_TREND_IN_PERIOD',
  PROJECT_LIST_PROGRESS = 'PROJECT_LIST_PROGRESS',
  PROJECT_LIST_PROFIT_COMPARISON = 'PROJECT_LIST_PROFIT_COMPARISON',
  INVOICE_UPLOAD = 'INVOICE_UPLOAD',
  INVOICE_LIST_UNBOUNDED = 'INVOICE_LIST_UNBOUNDED',
  INVOICE_GET_BY_ID = 'INVOICE_GET_BY_ID',
  OCR_RESULT_GET_BY_ID = 'OCR_RESULT_GET_BY_ID',
  ASSET_MANAGEMENT_LIST = 'ASSET_MANAGEMENT_LIST',
  ASSET_MANAGEMENT_ADD = 'ASSET_MANAGEMENT_ADD',
  ASSET_MANAGEMENT_GET_BY_ID = 'ASSET_MANAGEMENT_GET_BY_ID',
  ASSET_MANAGEMENT_UPDATE = 'ASSET_MANAGEMENT_UPDATE',
  JOURNAL_GENERATE = 'JOURNAL_GENERATE',
  JOURNAL_GET_PROGRESS_STATUS = 'JOURNAL_GET_PROGRESS_STATUS',
  JOURNAL_GET_PREVIEW_BY_ID = 'JOURNAL_GET_PREVIEW_BY_ID',
  JOURNAL_UPDATE = 'JOURNAL_UPDATE',
  JOURNAL_DELETE = 'JOURNAL_DELETE',
  JOURNAL_LIST_PROGRESS_STATUS = 'JOURNAL_LIST_PROGRESS_STATUS',
  JOURNAL_LIST = 'JOURNAL_LIST',
  JOURNAL_LIST_UNPROCESSED = 'JOURNAL_LIST_UNPROCESSED',
  JOURNAL_GET_BY_ID = 'JOURNAL_GET_BY_ID',
  VOUCHER_GENERATE = 'VOUCHER_GENERATE',
  VOUCHER_LIST = 'VOUCHER_LIST',
  REPORT_LIST_PENDING = 'REPORT_LIST_PENDING',
  REPORT_LIST_GENERATED = 'REPORT_LIST_GENERATED',
  REPORT_FINANCIAL_GET_BY_ID = 'REPORT_FINANCIAL_GET_BY_ID',
  REPORT_ANALYSIS_GET_BY_ID = 'REPORT_ANALYSIS_GET_BY_ID',
  REPORT_GENERATE_FINANCIAL = 'REPORT_GENERATE_FINANCIAL',
  REPORT_GENERATE_ANALYSIS = 'REPORT_GENERATE_ANALYSIS',
}

export enum APIPath {
  SIGN_UP = `${apiPrefix}/sign-up`,
  SIGN_IN = `${apiPrefix}/sign-in`,
  SIGN_OUT = `${apiPrefix}/sign-out`,
  EMAIL = `${apiPrefix}/email`,
  USER_GET_BY_ID = `${apiPrefix}/user/:userId`,
  USER_UPDATE = `${apiPrefix}/user/:userId`,
  COMPANY_LIST = `${apiPrefix}/company`,
  COMPANY_ADD = `${apiPrefix}/company`,
  COMPANY_ADD_BY_INVITATION_CODE = `${apiPrefix}/user/:userId/invitation`,
  COMPANY_SELECT = `${apiPrefix}/company/:companyId/select`,
  PROFIT_GET_INSIGHT = `${apiPrefix}/company/:companyId/profit_insight`,
  INCOME_EXPENSE_GET_TREND_IN_PERIOD = `${apiPrefix}/company/:companyId/income_expense_trend`,
  LABOR_COST_CHART = `${apiPrefix}/company/:companyId/labor_cost_chart`,
  PROJECT_LIST_PROGRESS = `${apiPrefix}/company/:companyId/project_progress`,
  PROJECT_LIST_PROFIT_COMPARISON = `${apiPrefix}/company/:companyId/profit_comparison`,
  INVOICE_UPLOAD = `${apiPrefix}/company/:companyId/invoice`,
  INVOICE_LIST_UNBOUNDED = `${apiPrefix}/company/:companyId/invoice_unbounded`,
  INVOICE_GET_BY_ID = `${apiPrefix}/company/:companyId/invoice/:invoiceId`,
  OCR_RESULT_GET_BY_ID = `${apiPrefix}/company/:companyId/OCR/:ocrResultId`,
  ASSET_MANAGEMENT_LIST = `${apiPrefix}/company/:companyId/asset_management`,
  ASSET_MANAGEMENT_ADD = `${apiPrefix}/company/:companyId/asset_management`,
  ASSET_MANAGEMENT_GET_BY_ID = `${apiPrefix}/company/:companyId/asset_management/:assetId`,
  ASSET_MANAGEMENT_UPDATE = `${apiPrefix}/company/:companyId/asset_management/:assetId`,
  JOURNAL_GENERATE = `${apiPrefix}/company/:companyId/voucher`,
  JOURNAL_GET_PROGRESS_STATUS = `${apiPrefix}/company/:companyId/voucher/:voucherId/status`,
  JOURNAL_GET_PREVIEW_BY_ID = `${apiPrefix}/company/:companyId/voucher/:voucherId`,
  JOURNAL_UPDATE = `${apiPrefix}/company/:companyId/voucher/:voucherId`,
  JOURNAL_DELETE = `${apiPrefix}/company/:companyId/voucher/:voucherId`,
  JOURNAL_LIST_PROGRESS_STATUS = `${apiPrefix}/company/:companyId/voucher_status`,
  JOURNAL_LIST = `${apiPrefix}/company/:companyId/journal`,
  JOURNAL_LIST_UNPROCESSED = `${apiPrefix}/company/:companyId/unprocess_journal`,
  JOURNAL_GET_BY_ID = `${apiPrefix}/company/:companyId/journal/:journalId`,
  VOUCHER_GENERATE = `${apiPrefix}/company/:companyId/journal`,
  VOUCHER_LIST = `${apiPrefix}/company/:companyId/journal`,
  REPORT_LIST_PENDING = `${apiPrefix}/company/:companyId/report_pending`,
  REPORT_LIST_GENERATED = `${apiPrefix}/company/:companyId/report_generated`,
  REPORT_FINANCIAL_GET_BY_ID = `${apiPrefix}/company/:companyId/report_financial/:reportId`,
  REPORT_ANALYSIS_GET_BY_ID = `${apiPrefix}/company/:companyId/report_analysis/:reportId`,
  REPORT_GENERATE_FINANCIAL = `${apiPrefix}/company/:companyId/report_financial`,
  REPORT_GENERATE_ANALYSIS = `${apiPrefix}/company/:companyId/report_analysis`,
}

export const APIConfig: Record<IAPIName, IAPIConfig> = {
  [APIName.SIGN_UP]: {
    name: APIName.SIGN_UP,
    method: HttpMethod.POST,
    path: APIPath.SIGN_UP,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.SIGN_IN]: {
    name: APIName.SIGN_IN,
    method: HttpMethod.POST,
    path: APIPath.SIGN_IN,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.SIGN_OUT]: {
    name: APIName.SIGN_OUT,
    method: HttpMethod.POST,
    path: APIPath.SIGN_OUT,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.EMAIL]: {
    name: APIName.EMAIL,
    method: HttpMethod.POST,
    path: APIPath.EMAIL,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.USER_GET_BY_ID]: {
    name: APIName.USER_GET_BY_ID,
    method: HttpMethod.GET,
    path: APIPath.USER_GET_BY_ID,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.INVOICE_GET_BY_ID]: {
    name: APIName.INVOICE_GET_BY_ID,
    method: HttpMethod.GET,
    path: APIPath.INVOICE_GET_BY_ID,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.INVOICE_UPLOAD]: {
    name: APIName.INVOICE_UPLOAD,
    method: HttpMethod.POST,
    path: APIPath.INVOICE_UPLOAD,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.VOUCHER_GENERATE]: {
    name: APIName.VOUCHER_GENERATE,
    method: HttpMethod.POST,
    path: APIPath.VOUCHER_GENERATE,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.JOURNAL_GET_PROGRESS_STATUS]: {
    name: APIName.JOURNAL_GET_PROGRESS_STATUS,
    method: HttpMethod.GET,
    path: APIPath.JOURNAL_GET_PROGRESS_STATUS,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.JOURNAL_GET_PREVIEW_BY_ID]: {
    name: APIName.JOURNAL_GET_PREVIEW_BY_ID,
    method: HttpMethod.GET,
    path: APIPath.JOURNAL_GET_PREVIEW_BY_ID,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.VOUCHER_LIST]: {
    name: APIName.VOUCHER_LIST,
    method: HttpMethod.GET,
    path: APIPath.VOUCHER_LIST,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.JOURNAL_GENERATE]: {
    name: APIName.JOURNAL_GENERATE,
    method: HttpMethod.POST,
    path: APIPath.JOURNAL_GENERATE,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.JOURNAL_LIST]: {
    name: APIName.JOURNAL_LIST,
    method: HttpMethod.GET,
    path: APIPath.JOURNAL_LIST,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.JOURNAL_GET_BY_ID]: {
    name: APIName.JOURNAL_GET_BY_ID,
    method: HttpMethod.GET,
    path: APIPath.JOURNAL_GET_BY_ID,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  USER_UPDATE: {
    name: APIName.USER_UPDATE,
    method: HttpMethod.PUT,
    path: APIPath.USER_UPDATE,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  COMPANY_LIST: {
    name: APIName.COMPANY_LIST,
    method: HttpMethod.GET,
    path: APIPath.COMPANY_LIST,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  COMPANY_ADD: {
    name: APIName.COMPANY_ADD,
    method: HttpMethod.POST,
    path: APIPath.COMPANY_ADD,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  COMPANY_ADD_BY_INVITATION_CODE: {
    name: APIName.COMPANY_ADD_BY_INVITATION_CODE,
    method: HttpMethod.PUT,
    path: APIPath.COMPANY_ADD_BY_INVITATION_CODE,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  PROFIT_GET_INSIGHT: {
    name: APIName.PROFIT_GET_INSIGHT,
    method: HttpMethod.GET,
    path: APIPath.PROFIT_GET_INSIGHT,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  INCOME_EXPENSE_GET_TREND_IN_PERIOD: {
    name: APIName.INCOME_EXPENSE_GET_TREND_IN_PERIOD,
    method: HttpMethod.GET,
    path: APIPath.INCOME_EXPENSE_GET_TREND_IN_PERIOD,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  PROJECT_LIST_PROGRESS: {
    name: APIName.PROJECT_LIST_PROGRESS,
    method: HttpMethod.GET,
    path: APIPath.PROJECT_LIST_PROGRESS,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  PROJECT_LIST_PROFIT_COMPARISON: {
    name: APIName.PROJECT_LIST_PROFIT_COMPARISON,
    method: HttpMethod.GET,
    path: APIPath.PROJECT_LIST_PROFIT_COMPARISON,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  INVOICE_LIST_UNBOUNDED: {
    name: APIName.INVOICE_LIST_UNBOUNDED,
    method: HttpMethod.GET,
    path: APIPath.INVOICE_LIST_UNBOUNDED,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  ASSET_MANAGEMENT_LIST: {
    name: APIName.ASSET_MANAGEMENT_LIST,
    method: HttpMethod.GET,
    path: APIPath.ASSET_MANAGEMENT_LIST,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  ASSET_MANAGEMENT_ADD: {
    name: APIName.ASSET_MANAGEMENT_ADD,
    method: HttpMethod.POST,
    path: APIPath.ASSET_MANAGEMENT_ADD,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  ASSET_MANAGEMENT_GET_BY_ID: {
    name: APIName.ASSET_MANAGEMENT_GET_BY_ID,
    method: HttpMethod.GET,
    path: APIPath.ASSET_MANAGEMENT_GET_BY_ID,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  ASSET_MANAGEMENT_UPDATE: {
    name: APIName.ASSET_MANAGEMENT_UPDATE,
    method: HttpMethod.PUT,
    path: APIPath.ASSET_MANAGEMENT_UPDATE,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  JOURNAL_UPDATE: {
    name: APIName.JOURNAL_UPDATE,
    method: HttpMethod.PUT,
    path: APIPath.JOURNAL_UPDATE,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  JOURNAL_DELETE: {
    name: APIName.JOURNAL_DELETE,
    method: HttpMethod.DELETE,
    path: APIPath.JOURNAL_DELETE,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  JOURNAL_LIST_PROGRESS_STATUS: {
    name: APIName.JOURNAL_LIST_PROGRESS_STATUS,
    method: HttpMethod.GET,
    path: APIPath.JOURNAL_LIST_PROGRESS_STATUS,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.COMPANY_SELECT]: {
    name: APIName.COMPANY_SELECT,
    method: HttpMethod.PUT,
    path: APIPath.COMPANY_SELECT,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  REPORT_LIST_PENDING: {
    name: APIName.REPORT_LIST_PENDING,
    method: HttpMethod.GET,
    path: APIPath.REPORT_LIST_PENDING,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  REPORT_LIST_GENERATED: {
    name: APIName.REPORT_LIST_GENERATED,
    method: HttpMethod.GET,
    path: APIPath.REPORT_LIST_GENERATED,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },

  [APIName.REPORT_FINANCIAL_GET_BY_ID]: {
    name: APIName.REPORT_FINANCIAL_GET_BY_ID,
    method: HttpMethod.GET,
    path: APIPath.REPORT_FINANCIAL_GET_BY_ID,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.REPORT_ANALYSIS_GET_BY_ID]: {
    name: APIName.REPORT_ANALYSIS_GET_BY_ID,
    method: HttpMethod.GET,
    path: APIPath.REPORT_ANALYSIS_GET_BY_ID,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.REPORT_GENERATE_FINANCIAL]: {
    name: APIName.REPORT_GENERATE_FINANCIAL,
    method: HttpMethod.POST,
    path: APIPath.REPORT_GENERATE_FINANCIAL,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.REPORT_GENERATE_ANALYSIS]: {
    name: APIName.REPORT_GENERATE_ANALYSIS,
    method: HttpMethod.POST,
    path: APIPath.REPORT_GENERATE_ANALYSIS,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.LABOR_COST_CHART]: {
    name: APIName.LABOR_COST_CHART,
    method: HttpMethod.GET,
    path: APIPath.LABOR_COST_CHART,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.JOURNAL_LIST_UNPROCESSED]: {
    name: APIName.JOURNAL_LIST_UNPROCESSED,
    method: HttpMethod.GET,
    path: APIPath.JOURNAL_LIST_UNPROCESSED,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
  [APIName.OCR_RESULT_GET_BY_ID]: {
    name: APIName.OCR_RESULT_GET_BY_ID,
    method: HttpMethod.GET,
    path: APIPath.OCR_RESULT_GET_BY_ID,
    input: {
      header: {},
      body: {},
      params: {},
      query: {},
    },
    output: {},
    useWorker: false,
  },
};
