import { APIName } from '@/constants/api_connection';

export enum AuthFunctionsKeysNew {
  user = 'user',
  admin = 'admin',
  owner = 'owner',
  superAdmin = 'superAdmin',
  CompanyAdminMatch = 'CompanyAdminMatch',
  projectCompanyMatch = 'projectCompanyMatch',
}

// ToDo: (20241111 - Jacky) Add more auth functions
export const AUTH_CHECK = {
  [APIName.COMPANY_LIST]: [AuthFunctionsKeysNew.user],
  [APIName.CREATE_COMPANY]: [AuthFunctionsKeysNew.user],
  [APIName.COMPANY_SELECT]: [AuthFunctionsKeysNew.user],
  [APIName.COMPANY_GET_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.COMPANY_UPDATE]: [AuthFunctionsKeysNew.user],
  [APIName.COMPANY_DELETE]: [AuthFunctionsKeysNew.user],
  [APIName.COMPANY_SETTING_GET]: [AuthFunctionsKeysNew.user],
  [APIName.COMPANY_SETTING_UPDATE]: [AuthFunctionsKeysNew.user],
  [APIName.COUNTERPARTY_LIST]: [AuthFunctionsKeysNew.user],
  [APIName.COUNTERPARTY_ADD]: [AuthFunctionsKeysNew.user],
  [APIName.COUNTERPARTY_GET_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.COUNTERPARTY_UPDATE]: [AuthFunctionsKeysNew.user],
  [APIName.COUNTERPARTY_DELETE]: [AuthFunctionsKeysNew.user],
  [APIName.USER_PENDING_TASK_GET]: [AuthFunctionsKeysNew.user],
  [APIName.COMPANY_PENDING_TASK_GET]: [AuthFunctionsKeysNew.user],
  [APIName.USER_ROLE_LIST]: [AuthFunctionsKeysNew.user],
  [APIName.USER_SELECT_ROLE]: [AuthFunctionsKeysNew.user],
  [APIName.USER_CREATE_ROLE]: [AuthFunctionsKeysNew.user],
  [APIName.ROLE_LIST]: [AuthFunctionsKeysNew.user],
  [APIName.NEWS_LIST]: [AuthFunctionsKeysNew.user],
  [APIName.CREATE_NEWS]: [AuthFunctionsKeysNew.user],
  [APIName.NEWS_GET_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.TODO_LIST]: [AuthFunctionsKeysNew.user],
  [APIName.CREATE_TODO]: [AuthFunctionsKeysNew.user],
  [APIName.TODO_GET_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.TODO_UPDATE]: [AuthFunctionsKeysNew.user],
  [APIName.TODO_DELETE]: [AuthFunctionsKeysNew.user],
  [APIName.ACCOUNTING_SETTING_GET]: [AuthFunctionsKeysNew.user],
  [APIName.ACCOUNTING_SETTING_UPDATE]: [AuthFunctionsKeysNew.user],
  [APIName.USER_SETTING_GET]: [AuthFunctionsKeysNew.user],
  [APIName.USER_SETTING_UPDATE]: [AuthFunctionsKeysNew.user],
  [APIName.USER_ACTION_LOG_LIST]: [AuthFunctionsKeysNew.user],
  [APIName.VOUCHER_POST_V2]: [AuthFunctionsKeysNew.user],
  [APIName.VOUCHER_LIST_V2]: [AuthFunctionsKeysNew.user],
  [APIName.TRIAL_BALANCE_LIST]: [AuthFunctionsKeysNew.user],
  [APIName.VOUCHER_GET_BY_ID_V2]: [AuthFunctionsKeysNew.user],
  [APIName.VOUCHER_PUT_V2]: [AuthFunctionsKeysNew.user],
  [APIName.VOUCHER_DELETE_V2]: [AuthFunctionsKeysNew.user],
  [APIName.REVERSE_LINE_ITEM_GET_BY_ACCOUNT_V2]: [AuthFunctionsKeysNew.user],
  [APIName.VOUCHER_LIST_GET_BY_ACCOUNT_V2]: [AuthFunctionsKeysNew.user],
  [APIName.ASK_AI_RESULT_V2]: [AuthFunctionsKeysNew.user],
  [APIName.CERTIFICATE_LIST_V2]: [AuthFunctionsKeysNew.user],
  [APIName.CERTIFICATE_POST_V2]: [AuthFunctionsKeysNew.user],
};
