import { APIName } from '@/constants/api_connection';
import { UploadType } from './file';

export enum AuthFunctionsKeysNew {
  user = 'user',
  admin = 'admin',
  owner = 'owner',
  superAdmin = 'superAdmin',
  CompanyAdminMatch = 'CompanyAdminMatch',
  projectCompanyMatch = 'projectCompanyMatch',
}

export const AUTH_WHITELIST = {
  [APIName.FILE_UPLOAD]: { query: { type: UploadType.ROOM } },
};

// ToDo: (20241111 - Jacky) Add more auth functions
export const AUTH_CHECK = {
  [APIName.LIST_USER_COMPANY]: [AuthFunctionsKeysNew.user],
  [APIName.CREATE_USER_COMPANY]: [AuthFunctionsKeysNew.user],
  [APIName.COMPANY_SELECT]: [AuthFunctionsKeysNew.user],
  [APIName.COMPANY_GET_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.COMPANY_UPDATE]: [AuthFunctionsKeysNew.user],
  [APIName.COMPANY_DELETE]: [AuthFunctionsKeysNew.user],
  [APIName.COMPANY_SETTING_GET]: [AuthFunctionsKeysNew.user],
  [APIName.COMPANY_SETTING_UPDATE]: [AuthFunctionsKeysNew.user],
  [APIName.COUNTERPARTY_LIST]: [AuthFunctionsKeysNew.user],
  [APIName.COUNTERPARTY_ADD]: [AuthFunctionsKeysNew.user],
  [APIName.COUNTERPARTY_GET_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.COUNTERPARTY_UPDATE]: [AuthFunctionsKeysNew.user],
  [APIName.COUNTERPARTY_DELETE]: [AuthFunctionsKeysNew.user],
  [APIName.USER_PENDING_TASK_GET]: [AuthFunctionsKeysNew.user],
  [APIName.COMPANY_PENDING_TASK_GET]: [AuthFunctionsKeysNew.user],
  [APIName.USER_ROLE_LIST]: [AuthFunctionsKeysNew.user],
  [APIName.USER_SELECT_ROLE]: [AuthFunctionsKeysNew.user],
  [APIName.USER_CREATE_ROLE]: [AuthFunctionsKeysNew.user],
  [APIName.ROLE_LIST]: [AuthFunctionsKeysNew.user],
  [APIName.NEWS_LIST]: [AuthFunctionsKeysNew.user],
  [APIName.CREATE_NEWS]: [AuthFunctionsKeysNew.user],
  [APIName.NEWS_GET_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.TODO_LIST]: [AuthFunctionsKeysNew.user],
  [APIName.CREATE_TODO]: [AuthFunctionsKeysNew.user],
  [APIName.TODO_GET_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.TODO_UPDATE]: [AuthFunctionsKeysNew.user],
  [APIName.TODO_DELETE]: [AuthFunctionsKeysNew.user],
  [APIName.ACCOUNTING_SETTING_GET]: [AuthFunctionsKeysNew.user],
  [APIName.ACCOUNTING_SETTING_UPDATE]: [AuthFunctionsKeysNew.user],
  [APIName.USER_SETTING_GET]: [AuthFunctionsKeysNew.user],
  [APIName.USER_SETTING_UPDATE]: [AuthFunctionsKeysNew.user],
  [APIName.USER_ACTION_LOG_LIST]: [AuthFunctionsKeysNew.user],
  [APIName.VOUCHER_POST_V2]: [AuthFunctionsKeysNew.user],
  [APIName.VOUCHER_LIST_V2]: [AuthFunctionsKeysNew.user],
  [APIName.TRIAL_BALANCE_LIST]: [AuthFunctionsKeysNew.user],
  [APIName.VOUCHER_GET_BY_ID_V2]: [AuthFunctionsKeysNew.user],
  [APIName.VOUCHER_PUT_V2]: [AuthFunctionsKeysNew.user],
  [APIName.VOUCHER_DELETE_V2]: [AuthFunctionsKeysNew.user],
  [APIName.REVERSE_LINE_ITEM_GET_BY_ACCOUNT_V2]: [AuthFunctionsKeysNew.user],
  [APIName.VOUCHER_LIST_GET_BY_ACCOUNT_V2]: [AuthFunctionsKeysNew.user],
  [APIName.ASK_AI_RESULT_V2]: [AuthFunctionsKeysNew.user],
  [APIName.CERTIFICATE_LIST_V2]: [AuthFunctionsKeysNew.user],
  [APIName.CERTIFICATE_POST_V2]: [AuthFunctionsKeysNew.user],
  [APIName.CERTIFICATE_GET_V2]: [AuthFunctionsKeysNew.user],
  [APIName.ASSET_LIST_EXPORT]: [AuthFunctionsKeysNew.user],
  [APIName.FILE_EXPORT]: [AuthFunctionsKeysNew.user], // ToDo: (20241112 - Luphia) need to define the schema for file export
  [APIName.ROOM_ADD]: [AuthFunctionsKeysNew.user],
  [APIName.ROOM_GET_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.ROOM_DELETE]: [AuthFunctionsKeysNew.user],

  [APIName.AGREE_TO_TERMS]: [AuthFunctionsKeysNew.user],
  [APIName.CREATE_CHALLENGE]: [AuthFunctionsKeysNew.user],
  [APIName.SIGN_UP]: [AuthFunctionsKeysNew.user],
  [APIName.SIGN_IN]: [AuthFunctionsKeysNew.user],
  [APIName.SIGN_OUT]: [AuthFunctionsKeysNew.user],
  [APIName.EMAIL]: [AuthFunctionsKeysNew.user],
  [APIName.USER_GET_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.USER_UPDATE]: [AuthFunctionsKeysNew.user],
  [APIName.COMPANY_ADD]: [AuthFunctionsKeysNew.user],
  [APIName.COMPANY_GET]: [AuthFunctionsKeysNew.user],
  [APIName.COMPANY_ADD_BY_INVITATION_CODE]: [AuthFunctionsKeysNew.user],
  [APIName.CERTIFICATE_PUT_V2]: [AuthFunctionsKeysNew.user],
  [APIName.CERTIFICATE_DELETE_V2]: [AuthFunctionsKeysNew.user],
  [APIName.CERTIFICATE_DELETE__MULTIPLE_V2]: [AuthFunctionsKeysNew.user],
  [APIName.PROFIT_GET_INSIGHT]: [AuthFunctionsKeysNew.user],
  [APIName.INCOME_EXPENSE_GET_TREND_IN_PERIOD]: [AuthFunctionsKeysNew.user],
  [APIName.LABOR_COST_CHART]: [AuthFunctionsKeysNew.user],
  [APIName.PROFIT_GET_TREND_IN_PERIOD]: [AuthFunctionsKeysNew.user],
  [APIName.PROJECT_LIST_PROGRESS]: [AuthFunctionsKeysNew.user],
  [APIName.PROJECT_LIST_PROFIT_COMPARISON]: [AuthFunctionsKeysNew.user],
  [APIName.ASSET_MANAGEMENT_LIST]: [AuthFunctionsKeysNew.user],
  [APIName.ASSET_MANAGEMENT_ADD]: [AuthFunctionsKeysNew.user],
  [APIName.ASSET_MANAGEMENT_GET_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.ASSET_MANAGEMENT_UPDATE]: [AuthFunctionsKeysNew.user],
  [APIName.OCR_UPLOAD]: [AuthFunctionsKeysNew.user],
  [APIName.OCR_DELETE]: [AuthFunctionsKeysNew.user],
  [APIName.OCR_RESULT_GET_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.OCR_LIST]: [AuthFunctionsKeysNew.user],
  [APIName.INVOICE_CREATE]: [AuthFunctionsKeysNew.user],
  [APIName.INVOICE_UPDATE]: [AuthFunctionsKeysNew.user],
  [APIName.INVOICE_GET_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.ASK_AI_STATUS]: [AuthFunctionsKeysNew.user],
  [APIName.ASK_AI_RESULT]: [AuthFunctionsKeysNew.user],
  [APIName.ASK_AI_V2]: [AuthFunctionsKeysNew.user],
  [APIName.VOUCHER_CREATE]: [AuthFunctionsKeysNew.user],
  [APIName.VOUCHER_UPDATE]: [AuthFunctionsKeysNew.user],
  [APIName.VOUCHER_WAS_READ_V2]: [AuthFunctionsKeysNew.user],
  [APIName.JOURNAL_GET_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.JOURNAL_LIST]: [AuthFunctionsKeysNew.user],
  // [APIName.JOURNAL_UPDATE]: [AuthFunctionsKeysNew.user], // Info: (20240723 - Tzuhan)
  [APIName.JOURNAL_DELETE]: [AuthFunctionsKeysNew.user],
  [APIName.REPORT_LIST]: [AuthFunctionsKeysNew.user],
  [APIName.REPORT_GET_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.REPORT_GET_V2]: [AuthFunctionsKeysNew.user],
  [APIName.REPORT_GENERATE]: [AuthFunctionsKeysNew.user],
  [APIName.STATUS_INFO_GET]: [AuthFunctionsKeysNew.user],
  [APIName.ACCOUNT_LIST]: [AuthFunctionsKeysNew.user],
  [APIName.FILE_UPLOAD]: [AuthFunctionsKeysNew.user],
  [APIName.PUBLIC_FILE_UPLOAD]: [AuthFunctionsKeysNew.user],
  [APIName.FILE_DELETE]: [AuthFunctionsKeysNew.user],
  [APIName.FILE_GET]: [AuthFunctionsKeysNew.user],
  [APIName.ROLE_GET_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.ROLE_DELETE]: [AuthFunctionsKeysNew.user],
  [APIName.ROLE_UPDATE]: [AuthFunctionsKeysNew.user],
  [APIName.KYC_UPLOAD]: [AuthFunctionsKeysNew.user],
  [APIName.ACCOUNT_GET_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.CREATE_NEW_SUB_ACCOUNT]: [AuthFunctionsKeysNew.user],
  [APIName.UPDATE_ACCOUNT_INFO_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.DELETE_ACCOUNT_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.TRANSFER_OWNER]: [AuthFunctionsKeysNew.user],
  [APIName.PROJECT_LIST]: [AuthFunctionsKeysNew.user],
  [APIName.CREATE_PROJECT]: [AuthFunctionsKeysNew.user],
  [APIName.GET_PROJECT_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.UPDATE_PROJECT_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.PUBLIC_KEY_GET]: [AuthFunctionsKeysNew.user],
  [APIName.ZOD_EXAMPLE]: [AuthFunctionsKeysNew.user], // Info: (20240909 - Murky) This is a Zod example, to demonstrate how to use Zod schema to validate data.
  [APIName.CERTIFICATE_LIST]: [AuthFunctionsKeysNew.user],
  [APIName.PUSHER]: [AuthFunctionsKeysNew.user],
  [APIName.ENCRYPT]: [AuthFunctionsKeysNew.user],
  [APIName.DECRYPT]: [AuthFunctionsKeysNew.user],
  [APIName.ASSET_LIST_V2]: [AuthFunctionsKeysNew.user],
  [APIName.ASSET_GET_BY_ID_V2]: [AuthFunctionsKeysNew.user],
  [APIName.CREATE_ASSET_V2]: [AuthFunctionsKeysNew.user],
  [APIName.DELETE_ASSET_V2]: [AuthFunctionsKeysNew.user],
  [APIName.UPDATE_ASSET_V2]: [AuthFunctionsKeysNew.user],
  [APIName.ASSET_SUGGESTED_NUMBER_GET_BY_TYPE]: [AuthFunctionsKeysNew.user],
  [APIName.IP_LIST]: [AuthFunctionsKeysNew.user],
  [APIName.LEDGER_LIST]: [AuthFunctionsKeysNew.user],
};
