import { APIName } from '@/constants/api_connection';
import { UploadType } from '@/constants/file';

export enum AuthFunctionsKeysNew {
  user = 'user',
  admin = 'admin',
  owner = 'owner',
  superAdmin = 'superAdmin',
  CompanyAdminMatch = 'CompanyAdminMatch',
  projectCompanyMatch = 'projectCompanyMatch',
  internal = 'internal',
}

export const AUTH_WHITELIST = {
  [APIName.FILE_UPLOAD]: { query: { type: UploadType.ROOM } },
  [APIName.ROOM_GET_PUBLIC_KEY_BY_ID]: { query: {} },
  [APIName.STATUS_INFO_GET]: { query: {} },
  [APIName.REPORT_GET_BY_ID]: { query: {} },
  [APIName.PAYMENT_METHOD_REGISTER_CALLBACK_OEN]: { query: {} },
};

// ToDo: (20241111 - Jacky) Add more auth functions
export const AUTH_CHECK: Record<APIName, AuthFunctionsKeysNew[]> = {
  [APIName.CREATE_ACCOUNT_BOOK]: [AuthFunctionsKeysNew.user],
  [APIName.DELETE_ACCOUNT_BOOK]: [AuthFunctionsKeysNew.user],
  [APIName.ACCOUNT_BOOK_SEARCH_BY_NAME_OR_TAX_ID]: [AuthFunctionsKeysNew.user],
  [APIName.COUNTERPARTY_LIST]: [AuthFunctionsKeysNew.user],
  [APIName.COUNTERPARTY_ADD]: [AuthFunctionsKeysNew.user],
  [APIName.COUNTERPARTY_GET_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.COUNTERPARTY_UPDATE]: [AuthFunctionsKeysNew.user],
  [APIName.COUNTERPARTY_DELETE]: [AuthFunctionsKeysNew.user],
  [APIName.USER_PENDING_TASK_GET]: [AuthFunctionsKeysNew.user],
  [APIName.ACCOUNT_BOOK_PENDING_TASK_GET]: [AuthFunctionsKeysNew.user],
  [APIName.USER_ROLE_LIST]: [AuthFunctionsKeysNew.user],
  [APIName.USER_SELECT_ROLE]: [AuthFunctionsKeysNew.user],
  [APIName.USER_CREATE_ROLE]: [AuthFunctionsKeysNew.user],
  [APIName.ROLE_LIST]: [AuthFunctionsKeysNew.user],
  [APIName.NEWS_LIST]: [AuthFunctionsKeysNew.user],
  [APIName.CREATE_NEWS]: [AuthFunctionsKeysNew.user],
  [APIName.NEWS_GET_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.TODO_LIST]: [AuthFunctionsKeysNew.user],
  [APIName.CREATE_TODO]: [AuthFunctionsKeysNew.user],
  [APIName.TODO_GET_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.UPDATE_TODO]: [AuthFunctionsKeysNew.user],
  [APIName.DELETE_TODO]: [AuthFunctionsKeysNew.user],
  [APIName.ACCOUNTING_SETTING_GET]: [AuthFunctionsKeysNew.user],
  [APIName.ACCOUNTING_SETTING_UPDATE]: [AuthFunctionsKeysNew.user],
  [APIName.USER_SETTING_GET]: [AuthFunctionsKeysNew.user],
  [APIName.USER_SETTING_UPDATE]: [AuthFunctionsKeysNew.user],
  [APIName.USER_ACTION_LOG_LIST]: [AuthFunctionsKeysNew.user],
  [APIName.VOUCHER_POST_V2]: [AuthFunctionsKeysNew.user],
  [APIName.VOUCHER_LIST_V2]: [AuthFunctionsKeysNew.user],
  [APIName.TRIAL_BALANCE_LIST]: [AuthFunctionsKeysNew.user],
  [APIName.VOUCHER_GET_BY_ID_V2]: [AuthFunctionsKeysNew.user],
  [APIName.VOUCHER_PUT_V2]: [AuthFunctionsKeysNew.user],
  [APIName.VOUCHER_DELETE_V2]: [AuthFunctionsKeysNew.user],
  [APIName.REVERSE_LINE_ITEM_GET_BY_ACCOUNT_V2]: [AuthFunctionsKeysNew.user],
  [APIName.VOUCHER_LIST_GET_BY_ACCOUNT_V2]: [AuthFunctionsKeysNew.user],
  [APIName.ASK_AI_RESULT_V2]: [AuthFunctionsKeysNew.user],
  [APIName.LIST_INVOICE_RC2]: [AuthFunctionsKeysNew.user],
  [APIName.LIST_INVOICE_RC2_INPUT]: [AuthFunctionsKeysNew.user],
  [APIName.CREATE_INVOICE_RC2_INPUT]: [AuthFunctionsKeysNew.user],
  [APIName.GET_INVOICE_RC2_INPUT]: [AuthFunctionsKeysNew.user],
  [APIName.UPDATE_INVOICE_RC2_INPUT]: [AuthFunctionsKeysNew.user],
  [APIName.DELETE_INVOICE_RC2_INPUT]: [AuthFunctionsKeysNew.user],
  [APIName.LIST_INVOICE_RC2_OUTPUT]: [AuthFunctionsKeysNew.user],
  [APIName.CREATE_INVOICE_RC2_OUTPUT]: [AuthFunctionsKeysNew.user],
  [APIName.GET_INVOICE_RC2_OUTPUT]: [AuthFunctionsKeysNew.user],
  [APIName.UPDATE_INVOICE_RC2_OUTPUT]: [AuthFunctionsKeysNew.user],
  [APIName.DELETE_INVOICE_RC2_OUTPUT]: [AuthFunctionsKeysNew.user],
  [APIName.CERTIFICATE_LIST_V2]: [AuthFunctionsKeysNew.user],
  [APIName.CERTIFICATE_POST_V2]: [AuthFunctionsKeysNew.user],
  [APIName.CERTIFICATE_GET_V2]: [AuthFunctionsKeysNew.user],
  [APIName.CERTIFICATE_DELETE_MULTIPLE_V2]: [AuthFunctionsKeysNew.user],
  [APIName.INVOICE_POST_V2]: [AuthFunctionsKeysNew.user],
  [APIName.INVOICE_PUT_V2]: [AuthFunctionsKeysNew.user],
  [APIName.ASSET_LIST_EXPORT]: [AuthFunctionsKeysNew.user],
  [APIName.FILE_EXPORT]: [AuthFunctionsKeysNew.user], // ToDo: (20241112 - Luphia) need to define the schema for file export
  [APIName.ROOM_ADD]: [AuthFunctionsKeysNew.user],
  [APIName.ROOM_GET_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.ROOM_GET_PUBLIC_KEY_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.ROOM_DELETE]: [AuthFunctionsKeysNew.user],
  [APIName.AGREE_TO_TERMS]: [AuthFunctionsKeysNew.user],
  [APIName.SIGN_IN]: [AuthFunctionsKeysNew.user],
  [APIName.SIGN_OUT]: [AuthFunctionsKeysNew.user],
  [APIName.EMAIL]: [AuthFunctionsKeysNew.user],
  [APIName.USER_LIST]: [AuthFunctionsKeysNew.user],
  [APIName.USER_GET_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.USER_UPDATE]: [AuthFunctionsKeysNew.user],
  [APIName.CERTIFICATE_PUT_V2]: [AuthFunctionsKeysNew.user],
  [APIName.CERTIFICATE_DELETE_V2]: [AuthFunctionsKeysNew.user],
  [APIName.IMAGE_GET_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.ASK_AI_STATUS]: [AuthFunctionsKeysNew.user],
  [APIName.ASK_AI_V2]: [AuthFunctionsKeysNew.user],
  [APIName.JOURNAL_LIST]: [AuthFunctionsKeysNew.user],
  [APIName.REPORT_LIST]: [AuthFunctionsKeysNew.user],
  [APIName.REPORT_GET_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.REPORT_GET_V2]: [AuthFunctionsKeysNew.user],
  [APIName.REPORT_GENERATE]: [AuthFunctionsKeysNew.user],
  [APIName.STATUS_INFO_GET]: [AuthFunctionsKeysNew.user],
  [APIName.ACCOUNT_LIST]: [AuthFunctionsKeysNew.user],
  [APIName.FILE_UPLOAD]: [AuthFunctionsKeysNew.user],
  [APIName.FILE_DELETE]: [AuthFunctionsKeysNew.user],
  [APIName.FILE_DELETE_V2]: [AuthFunctionsKeysNew.user],
  [APIName.FILE_GET]: [AuthFunctionsKeysNew.user],
  [APIName.FILE_PUT_V2]: [AuthFunctionsKeysNew.user],
  [APIName.KYC_UPLOAD]: [AuthFunctionsKeysNew.user],
  [APIName.ACCOUNT_GET_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.CREATE_NEW_SUB_ACCOUNT]: [AuthFunctionsKeysNew.user],
  [APIName.UPDATE_ACCOUNT_INFO_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.DELETE_ACCOUNT_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.PUBLIC_KEY_GET]: [AuthFunctionsKeysNew.user],
  [APIName.ZOD_EXAMPLE]: [AuthFunctionsKeysNew.user], // Info: (20240909 - Murky) This is a Zod example, to demonstrate how to use Zod schema to validate data.
  [APIName.CERTIFICATE_LIST]: [AuthFunctionsKeysNew.user],
  [APIName.PUSHER_AUTH]: [AuthFunctionsKeysNew.user],
  [APIName.ASSET_LIST_V2]: [AuthFunctionsKeysNew.user],
  [APIName.ASSET_GET_BY_ID_V2]: [AuthFunctionsKeysNew.user],
  [APIName.CREATE_ASSET_V2]: [AuthFunctionsKeysNew.user],
  [APIName.DELETE_ASSET_V2]: [AuthFunctionsKeysNew.user],
  [APIName.UPDATE_ASSET_V2]: [AuthFunctionsKeysNew.user],
  [APIName.LEDGER_LIST]: [AuthFunctionsKeysNew.user],
  [APIName.TRIAL_BALANCE_EXPORT]: [AuthFunctionsKeysNew.user],
  [APIName.CREATE_ASSET_BULK]: [AuthFunctionsKeysNew.user],
  [APIName.LEDGER_EXPORT]: [AuthFunctionsKeysNew.user],
  [APIName.LIST_LOGIN_DEVICE]: [AuthFunctionsKeysNew.user],
  [APIName.REMOVE_LOGIN_DEVICE]: [AuthFunctionsKeysNew.user],

  [APIName.CREATE_TEAM]: [AuthFunctionsKeysNew.user],
  [APIName.LIST_TEAM]: [AuthFunctionsKeysNew.user],
  [APIName.GET_TEAM_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.UPDATE_TEAM_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.UPDATE_MEMBER]: [AuthFunctionsKeysNew.user],
  [APIName.DELETE_MEMBER]: [AuthFunctionsKeysNew.user],
  [APIName.LIST_ACCOUNT_BOOK_BY_TEAM_ID]: [AuthFunctionsKeysNew.user],
  [APIName.LIST_MEMBER_BY_TEAM_ID]: [AuthFunctionsKeysNew.user],
  [APIName.INVITE_MEMBER_TO_TEAM]: [AuthFunctionsKeysNew.user],
  [APIName.ACCEPT_TEAM_INVITATION]: [AuthFunctionsKeysNew.user],
  [APIName.DECLINE_TEAM_INVITATION]: [AuthFunctionsKeysNew.user],
  [APIName.LEAVE_TEAM]: [AuthFunctionsKeysNew.user],
  [APIName.REQUEST_TRANSFER_ACCOUNT_BOOK]: [AuthFunctionsKeysNew.user],
  [APIName.CANCEL_TRANSFER_ACCOUNT_BOOK]: [AuthFunctionsKeysNew.user],
  [APIName.ACCEPT_TRANSFER_ACCOUNT_BOOK]: [AuthFunctionsKeysNew.user],
  [APIName.DECLINE_TRANSFER_ACCOUNT_BOOK]: [AuthFunctionsKeysNew.user],

  [APIName.LIST_TEAM_SUBSCRIPTION]: [AuthFunctionsKeysNew.user],
  [APIName.GET_SUBSCRIPTION_BY_TEAM_ID]: [AuthFunctionsKeysNew.user],
  [APIName.UPDATE_SUBSCRIPTION]: [AuthFunctionsKeysNew.user],
  [APIName.LIST_TEAM_INVOICE]: [AuthFunctionsKeysNew.user],
  [APIName.GET_SUBSCRIPTION_INVOICE_BY_TEAM_ID]: [AuthFunctionsKeysNew.user],

  [APIName.GET_CREDIT_CARD_INFO]: [AuthFunctionsKeysNew.user],
  [APIName.LIST_PAYMENT_PLAN]: [AuthFunctionsKeysNew.user],
  [APIName.VOUCHER_RESTORE_V2]: [AuthFunctionsKeysNew.user],

  [APIName.LIST_ACCOUNT_BOOK_BY_USER_ID]: [AuthFunctionsKeysNew.user],
  [APIName.LIST_SIMPLE_ACCOUNT_BOOK_BY_USER_ID]: [AuthFunctionsKeysNew.user],
  [APIName.CONNECT_ACCOUNT_BOOK_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.GET_ACCOUNT_BOOK_INFO_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.GET_ACCOUNT_BOOK_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.PUT_TEAM_ICON]: [AuthFunctionsKeysNew.user],
  [APIName.UPDATE_ACCOUNT_BOOK]: [AuthFunctionsKeysNew.user],

  [APIName.USER_PAYMENT_METHOD_LIST]: [AuthFunctionsKeysNew.user],
  [APIName.USER_PAYMENT_METHOD_CHARGE]: [AuthFunctionsKeysNew.user],
  [APIName.PAYMENT_METHOD_REGISTER_REDIRECT]: [AuthFunctionsKeysNew.user],
  [APIName.PAYMENT_METHOD_REGISTER_CALLBACK_OEN]: [AuthFunctionsKeysNew.user],
  [APIName.UPDATE_ACCOUNT_BOOK_INFO]: [AuthFunctionsKeysNew.user],
  [APIName.DISCONNECT_ACCOUNT_BOOK]: [AuthFunctionsKeysNew.user],
  [APIName.ACCOUNT_BOOK_PUT_ICON]: [AuthFunctionsKeysNew.user],
  [APIName.SEND_VERIFICATION_EMAIL]: [AuthFunctionsKeysNew.user],
  [APIName.VERIFY_CODE]: [AuthFunctionsKeysNew.user],

  [APIName.LIST_NOTIFICATION]: [AuthFunctionsKeysNew.user],
  [APIName.GET_NOTIFICATION_BY_ID]: [AuthFunctionsKeysNew.user],
  [APIName.READ_NOTIFICATION]: [AuthFunctionsKeysNew.user],

  [APIName.LIST_BAIFA_ACCOUNT_BOOK]: [AuthFunctionsKeysNew.internal],
  [APIName.LIST_BAIFA_VOUCHER]: [AuthFunctionsKeysNew.internal],

  [APIName.GET_VACANCY_BY_ID]: [AuthFunctionsKeysNew.user],
};
