export const BUSINESS_MONITOR_INDUSTRIES = {
  SEMICONDUCTOR: "SEMICONDUCTOR",
  COMPUTER_PERIPHERALS: "COMPUTER_PERIPHERALS",
  OPTOELECTRONICS: "OPTOELECTRONICS",
  COMMUNICATIONS: "COMMUNICATIONS",
  ELECTRONIC_COMPONENTS: "ELECTRONIC_COMPONENTS",
} as const;
