export enum DeductionType {
  DEDUCTIBLE_PURCHASE_AND_EXPENSE = 'DEDUCTIBLE_PURCHASE_AND_EXPENSE',
  DEDUCTIBLE_FIXED_ASSETS = 'DEDUCTIBLE_FIXED_ASSETS',
  NON_DEDUCTIBLE_PURCHASE_AND_EXPENSE = 'NON_DEDUCTIBLE_PURCHASE_AND_EXPENSE',
  NON_DEDUCTIBLE_FIXED_ASSETS = 'NON_DEDUCTIBLE_FIXED_ASSETS',
}
