export const IS_BUTTON_DISABLED_TEMP = true;

export const INTERVAL_NUMBER_ANIMATION_MOBILE = 1000;
export const INTERVAL_NUMBER_ANIMATION_DESKTOP = 10;

export const DEFAULT_DISPLAYED_USER_NAME = 'User';

export const NO_DATA_FOR_DEMO = false;

export const MONTH_LIST = [
  'DATE_PICKER.JAN',
  'DATE_PICKER.FEB',
  'DATE_PICKER.MAR',
  'DATE_PICKER.APR',
  'DATE_PICKER.MAY',
  'DATE_PICKER.JUN',
  'DATE_PICKER.JUL',
  'DATE_PICKER.AUG',
  'DATE_PICKER.SEP',
  'DATE_PICKER.OCT',
  'DATE_PICKER.NOV',
  'DATE_PICKER.DEC',
];

export const MONTH_ABR_LIST = [
  'DATE_PICKER.JAN_ABR',
  'DATE_PICKER.FEB_ABR',
  'DATE_PICKER.MAR_ABR',
  'DATE_PICKER.APR_ABR',
  'DATE_PICKER.MAY_ABR',
  'DATE_PICKER.JUN_ABR',
  'DATE_PICKER.JUL_ABR',
  'DATE_PICKER.AUG_ABR',
  'DATE_PICKER.SEP_ABR',
  'DATE_PICKER.OCT_ABR',
  'DATE_PICKER.NOV_ABR',
  'DATE_PICKER.DEC_ABR',
];

export const WEEK_LIST = [
  'DATE_PICKER.SUN',
  'DATE_PICKER.MON',
  'DATE_PICKER.TUE',
  'DATE_PICKER.WED',
  'DATE_PICKER.THU',
  'DATE_PICKER.FRI',
  'DATE_PICKER.SAT',
];

export const default30DayPeriod = {
  startTimeStamp: 0,
  endTimeStamp: 0,
};
