export enum EMAIL_LOGIN_ACTION {
  REGISTER = 'register',
  VERIFY = 'verify',
}

export const MAX_EMIL_LOGIN_ERROR_TIMES = 5;
export const EMAIL_LOGIN_REGISTER_COOLDOWN_IN_M = 3;
export const EMAIL_LOGIN_REGISTER_COOLDOWN_IN_S = EMAIL_LOGIN_REGISTER_COOLDOWN_IN_M * 60;
export const EMAIL_LOGIN_TOO_MANY_ATTEMPTS_COOLDOWN_IN_M = 10;
export const EMAIL_LOGIN_TOO_MANY_ATTEMPTS_COOLDOWN_IN_S =
  EMAIL_LOGIN_TOO_MANY_ATTEMPTS_COOLDOWN_IN_M * 60;
