export const ERROR_CODE = {
  UNAUTHORIZED_ACCESS: 401,
  RESOURCE_NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  INVALID_INPUT_PARAMETER: 422,
  INTERNAL_SERVICE_ERROR: 500,
  BAD_GATEWAY: 502,
  GATEWAY_TIMEOUT: 504,
};
