export enum MimeType {
  CSV = 'text/csv',
  PDF = 'application/pdf',
  DOCX = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  DOC = 'application/msword',
  PUB = 'application/x-mspublisher',
  TXT = 'text/plain',
  XSL = 'application/vnd.ms-excel',
  PPT = 'application/vnd.ms-powerpoint',

  MDB = 'application/x-msaccess',
  ZIP = 'application/zip',
  RAR = 'application/x-rar-compressed',
  ISO = 'application/x-iso9660-image',
  EXE = 'application/x-msdownload',
  // DLL = 'application/x-msdownload',
  PSD = 'application/x-photoshop',
  // AI = 'application/postscript',

  PS = 'application/postscript',
  CRD = 'application/x-mscardfile',
  SVG = 'image/svg+xml',
  // EPS = 'application/postscript',
  DWG = 'image/vnd.dwg',
  BMP = 'image/bmp',
  JPG = 'image/jpeg',
  TIFF = 'image/tiff',

  RAW = 'image/x-raw',
  PNG = 'image/png',
  GIF = 'image/gif',
  FLV = 'video/x-flv',
  AVI = 'video/x-msvideo',
  MPEG = 'video/mpeg',
  MOV = 'video/quicktime',
  MP4 = 'video/mp4',

  WMA = 'audio/x-ms-wma',
  MP3 = 'audio/mpeg',
  MID = 'audio/midi',
  WAV = 'audio/wav',
  JSON = 'application/json',
  RSS = 'application/rss+xml',
  XML = 'application/xml',
  HTML = 'text/html',
}
