export enum PAYMENT_METHOD_TYPE {
  MASTER = 'MASTER',
  VISA = 'VISA',
  JCB = 'JCB',
  UNIONPAY = 'UNIONPAY',
  AMERICAN_EXPRESS = 'AMERICAN_EXPRESS',
  DINERS_CLUB = 'DINERS_CLUB',
  DISCOVER = 'DISCOVER',
  OTHER = 'OTHER',
}
