export enum PAYMENT_METHOD_TYPE {
  MASTER = 'MASTER',
  VISA = 'VISA',
  JCB = 'JCB',
  UNIONPAY = 'UNIONPAY',
  AMERICAN_EXPRESS = 'AMERICAN_EXPRESS',
  DINERS_CLUB = 'DINERS_CLUB',
  DISCOVER = 'DISCOVER',
  OTHER = 'OTHER',
}

export enum PAYMENT_GATEWAY {
  OEN = 'OEN',
  HITRUST = 'HITRUST',
  STRIPE = 'STRIPE',
  PAYPAL = 'PAYPAL',
  LINE_PAY = 'LINE_PAY',
  ALIPAY = 'ALIPAY',
  WECHAT_PAY = 'WE',
}

export enum PAYEE {
  NAME = '墨沫有限公司',
  ADDRESS = '105402 臺北市松山區民生東路三段156號9樓',
  PHONE = '02-2546-6225',
  TAX_ID = '52650861',
}
