export enum PAYMENT_METHOD_TYPE {
  MASTER = 'MASTER',
  VISA = 'VISA',
  JCB = 'JCB',
  UNIONPAY = 'UNIONPAY',
  AMERICAN_EXPRESS = 'AMERICAN_EXPRESS',
  DINERS_CLUB = 'DINERS_CLUB',
  DISCOVER = 'DISCOVER',
  OTHER = 'OTHER',
}

export enum PAYMENT_GATEWAY {
  OEN = 'OEN',
  HITRUST = 'HITRUST',
  STRIPE = 'STRIPE',
  PAYPAL = 'PAYPAL',
  LINE_PAY = 'LINE_PAY',
  ALIPAY = 'ALIPAY',
  WECHAT_PAY = 'WE',
}
