enum SuccessCode {
  SUCCESS = '200ISF0000',
  SUCCESS_LIST = '200ISF0001',
  SUCCESS_GET = '200ISF0002',
  SUCCESS_UPDATE = '200ISF0003',
  SUCCESS_DELETE = '200ISF0004',
  CREATED = '201ISF0000',
}

enum ErrorCode {
  UNAUTHORIZED_ACCESS = '401ISF0000',
  RESOURCE_NOT_FOUND = '404ISF0000',
  AICH_SUCCESSFUL_RETURN_BUT_RESULT_IS_NULL = '404ISF0001',
  AICH_API_NOT_FOUND = '404ISF0002',
  METHOD_NOT_ALLOWED = '405ISF0000',
  INVALID_INPUT_PARAMETER = '422ISF0000',
  INVALID_INPUT_FORMDATA_IMAGE = '422ISF0001',
  INVALID_INPUT_INVOICE_BODY_TO_VOUCHER = '422ISF0002',
  INVALID_INPUT_VOUCHER_BODY_TO_JOURNAL = '422ISF0003',
  INTERNAL_SERVICE_ERROR = '500ISF0000',
  IMAGE_UPLOAD_FAILED_ERROR = '500ISF0001',
  DATABASE_CREATE_FAILED_ERROR = '500ISF0002',
  DATABASRE_READ_FAILED_ERROR = '500ISF0003',
  INVALID_STATUS_MESSAGE_ERROR = '511ISF0001',
  BAD_GATEWAY = '502ISF0000',
  BAD_GATEWAY_AICH_FAILED = '502ISF0001',
  BAD_GATEWAY_DATA_FROM_AICH_IS_INVALID_TYPE = '502ISF0002',
  BAD_GATEWAY_PRISMA_ERROR = '502ISF0003',
  GATEWAY_TIMEOUT = '504ISF0000',
}

export enum SuccessMessage {
  SUCCESS = 'Success',
  SUCCESS_LIST = 'List successfully',
  SUCCESS_GET = 'Get successfully',
  SUCCESS_UPDATE = 'Update successfully',
  SUCCESS_DELETE = 'Delete successfully',
  CREATED = 'Created successfully',
}

export enum ErrorMessage {
  UNAUTHORIZED_ACCESS = 'Unauthorized access',
  RESOURCE_NOT_FOUND = 'Resource not found',
  AICH_SUCCESSFUL_RETURN_BUT_RESULT_IS_NULL = 'AICH successful return but result is null',
  AICH_API_NOT_FOUND = 'AICH API not found',
  METHOD_NOT_ALLOWED = 'Method not allowed',
  INVALID_INPUT_PARAMETER = 'Invalid input parameter',
  INVALID_INPUT_FORMDATA_IMAGE = 'Invalid input formdata image',
  INVALID_INPUT_INVOICE_BODY_TO_VOUCHER = 'Invalid input invoice body to voucher',
  INVALID_INPUT_VOUCHER_BODY_TO_JOURNAL = 'Invalid input voucher body to journal',
  INTERNAL_SERVICE_ERROR = 'Internal service error',
  IMAGE_UPLOAD_FAILED_ERROR = 'Image upload failed',
  DATABASE_CREATE_FAILED_ERROR = 'Database create failed',
  DATABASRE_READ_FAILED_ERROR = 'Database read failed',
  INVALID_STATUS_MESSAGE_ERROR = 'Invalid Status Message',
  BAD_GATEWAY = 'Bad gateway',
  BAD_GATEWAY_AICH_FAILED = 'Bad gateway connect AICH failed',
  BAD_GATEWAY_DATA_FROM_AICH_IS_INVALID_TYPE = 'Bad gateway data from AICH is invalid type',
  BAD_GATEWAY_PRISMA_ERROR = 'Prisma related error',
  GATEWAY_TIMEOUT = 'Gateway timeout',
}

export const STATUS_MESSAGE = {
  ...SuccessMessage,
  ...ErrorMessage,
};

export const STATUS_CODE = {
  [STATUS_MESSAGE.SUCCESS]: SuccessCode.SUCCESS,
  [STATUS_MESSAGE.SUCCESS_LIST]: SuccessCode.SUCCESS_LIST,
  [STATUS_MESSAGE.SUCCESS_GET]: SuccessCode.SUCCESS_GET,
  [STATUS_MESSAGE.SUCCESS_UPDATE]: SuccessCode.SUCCESS_UPDATE,
  [STATUS_MESSAGE.SUCCESS_DELETE]: SuccessCode.SUCCESS_DELETE,
  [STATUS_MESSAGE.CREATED]: SuccessCode.CREATED,
  [STATUS_MESSAGE.UNAUTHORIZED_ACCESS]: ErrorCode.UNAUTHORIZED_ACCESS,
  [STATUS_MESSAGE.RESOURCE_NOT_FOUND]: ErrorCode.RESOURCE_NOT_FOUND,
  [STATUS_MESSAGE.AICH_SUCCESSFUL_RETURN_BUT_RESULT_IS_NULL]: ErrorCode.AICH_SUCCESSFUL_RETURN_BUT_RESULT_IS_NULL,
  [STATUS_MESSAGE.AICH_API_NOT_FOUND]: ErrorCode.AICH_API_NOT_FOUND,
  [STATUS_MESSAGE.METHOD_NOT_ALLOWED]: ErrorCode.METHOD_NOT_ALLOWED,
  [STATUS_MESSAGE.INVALID_INPUT_PARAMETER]: ErrorCode.INVALID_INPUT_PARAMETER,
  [STATUS_MESSAGE.INVALID_INPUT_INVOICE_BODY_TO_VOUCHER]:
    ErrorCode.INVALID_INPUT_INVOICE_BODY_TO_VOUCHER,
  [STATUS_MESSAGE.INVALID_INPUT_VOUCHER_BODY_TO_JOURNAL]:
    ErrorCode.INVALID_INPUT_VOUCHER_BODY_TO_JOURNAL,
  [STATUS_MESSAGE.INVALID_INPUT_FORMDATA_IMAGE]: ErrorCode.INVALID_INPUT_FORMDATA_IMAGE,
  [STATUS_MESSAGE.INTERNAL_SERVICE_ERROR]: ErrorCode.INTERNAL_SERVICE_ERROR,
  [STATUS_MESSAGE.DATABASE_CREATE_FAILED_ERROR]: ErrorCode.DATABASE_CREATE_FAILED_ERROR,
  [STATUS_MESSAGE.DATABASRE_READ_FAILED_ERROR]: ErrorCode.DATABASRE_READ_FAILED_ERROR,
  [STATUS_MESSAGE.IMAGE_UPLOAD_FAILED_ERROR]: ErrorCode.IMAGE_UPLOAD_FAILED_ERROR,
  [STATUS_MESSAGE.BAD_GATEWAY]: ErrorCode.BAD_GATEWAY,
  [STATUS_MESSAGE.BAD_GATEWAY_AICH_FAILED]: ErrorCode.BAD_GATEWAY_AICH_FAILED,
  [STATUS_MESSAGE.BAD_GATEWAY_DATA_FROM_AICH_IS_INVALID_TYPE]:
    ErrorCode.BAD_GATEWAY_DATA_FROM_AICH_IS_INVALID_TYPE,
  [STATUS_MESSAGE.BAD_GATEWAY_PRISMA_ERROR]: ErrorCode.BAD_GATEWAY_PRISMA_ERROR,
  [STATUS_MESSAGE.GATEWAY_TIMEOUT]: ErrorCode.GATEWAY_TIMEOUT,
  [STATUS_MESSAGE.INVALID_STATUS_MESSAGE_ERROR]: ErrorCode.INVALID_STATUS_MESSAGE_ERROR,
};
