enum SuccessCode {
  SUCCESS = '200ISF0000',
  SUCCESS_LIST = '200ISF0001',
  SUCCESS_GET = '200ISF0002',
  SUCCESS_UPDATE = '200ISF0003',
  SUCCESS_DELETE = '200ISF0004',
  CREATED = '201ISF0000',
}

enum ErrorCode {
  UNAUTHORIZED_ACCESS = '401ISF0000',
  RESOURCE_NOT_FOUND = '404ISF0000',
  METHOD_NOT_ALLOWED = '405ISF0000',
  INVALID_INPUT_PARAMETER = '422ISF0000',
  INTERNAL_SERVICE_ERROR = '500ISF0000',
  INVOICE_UPLOAD_FAILED_ERROR = '500ISF0001',
  INVALID_STATUS_CODE_ERROR = '511ISF0001',
  BAD_GATEWAY = '502ISF0000',
  GATEWAY_TIMEOUT = '504ISF0000',
}

export enum SuccessMessage {
  SUCCESS = 'Success',
  SUCCESS_LIST = 'List successfully',
  SUCCESS_GET = 'Get successfully',
  SUCCESS_UPDATE = 'Update successfully',
  SUCCESS_DELETE = 'Delete successfully',
  CREATED = 'Created successfully',
}

export enum ErrorMessage {
  UNAUTHORIZED_ACCESS = 'Unauthorized access',
  RESOURCE_NOT_FOUND = 'Resource not found',
  METHOD_NOT_ALLOWED = 'Method not allowed',
  INVALID_INPUT_PARAMETER = 'Invalid input parameter',
  INTERNAL_SERVICE_ERROR = 'Internal service error',
  INVOICE_UPLOAD_FAILED_ERROR = 'Invoice upload failed error',
  INVALID_STATUS_CODE_ERROR = 'Invalid Status Code',
  BAD_GATEWAY = 'Bad gateway',
  GATEWAY_TIMEOUT = 'Gateway timeout',
}

export const STATUS_CODE = {
  ...SuccessCode,
  ...ErrorCode,
};

export const STATUS_MESSAGE = {
  [STATUS_CODE.SUCCESS]: SuccessMessage.SUCCESS,
  [STATUS_CODE.SUCCESS_LIST]: SuccessMessage.SUCCESS_LIST,
  [STATUS_CODE.SUCCESS_GET]: SuccessMessage.SUCCESS_GET,
  [STATUS_CODE.SUCCESS_UPDATE]: SuccessMessage.SUCCESS_UPDATE,
  [STATUS_CODE.SUCCESS_DELETE]: SuccessMessage.SUCCESS_DELETE,
  [STATUS_CODE.CREATED]: SuccessMessage.CREATED,
  [STATUS_CODE.UNAUTHORIZED_ACCESS]: ErrorMessage.UNAUTHORIZED_ACCESS,
  [STATUS_CODE.RESOURCE_NOT_FOUND]: ErrorMessage.RESOURCE_NOT_FOUND,
  [STATUS_CODE.METHOD_NOT_ALLOWED]: ErrorMessage.METHOD_NOT_ALLOWED,
  [STATUS_CODE.INVALID_INPUT_PARAMETER]: ErrorMessage.INVALID_INPUT_PARAMETER,
  [STATUS_CODE.INTERNAL_SERVICE_ERROR]: ErrorMessage.INTERNAL_SERVICE_ERROR,
  [STATUS_CODE.INVOICE_UPLOAD_FAILED_ERROR]: ErrorMessage.INVOICE_UPLOAD_FAILED_ERROR,
  [STATUS_CODE.BAD_GATEWAY]: ErrorMessage.BAD_GATEWAY,
  [STATUS_CODE.GATEWAY_TIMEOUT]: ErrorMessage.GATEWAY_TIMEOUT,
  [STATUS_CODE.INVALID_STATUS_CODE_ERROR]: ErrorMessage.INVALID_STATUS_CODE_ERROR,
};
