export enum ToastId {
  TRIAL = 'toast-trial-version',
  INVITATION_SUCCESS = 'toast-invitation-success',
  ALPHA_TEST_REMINDER = 'toast-alpha-test-reminder',
  PROJECT_STAGE_UPDATE = 'toast-project-stage-update',
  ADD_ASSET_SUCCESS = 'toast-add-asset-success',
  ADD_ASSET_ERROR = 'toast-add-asset-error',
  DELETE_CERTIFICATE_SUCCESS = 'toast-delete-certificate-success',
  DELETE_CERTIFICATE_ERROR = 'toast-delete-certificate-error',
  TOKEN_NOT_PROVIDED = 'toast-token-not-provided',
  UPLOAD_CERTIFICATE_ERROR = 'toast-upload-certificate-error',
  UPLOAD_FILE_SUCCESS = 'toast-upload-file-success',
  UPLOAD_FILE_ERROR = 'toast-upload-file-error',
  NOTIFY_WEB_ERROR = 'toast-notify-web-error',
  ADD_COUNTERPARTY_SUCCESS = 'toast-add-counterparty-success',
  SAVE_CERTIFICATE_SUCCESS = 'toast-save-certificate-success',
}
