import { ProgressStatus } from '@/constants/account';

import { FileFolder } from '@/constants/file';

export interface IFile {
  id: number;
  name: string;
  size: number;
  existed: boolean;
}

export interface IFileBeta extends IFile {
  id: number;
  name: string;
  size: number;
  url: string;
}

// (20241021 - tzuhan) Info: only for frontend without confidential data
export interface IFileUIBeta {
  id: number | null;
  certificateId?: number;
  name: string;
  size: number;
  url: string;
  progress: number; // Info: (20240919 - tzuhan) 上傳進度（0-100）
  status: ProgressStatus; // Info: (20240919 - tzuhan) 是否暫停
}

/**
 * Info: (20241023 - Murky)
 * @description file entity interface specific for backend
 * @note use parsePrismaFileToFileEntity to convert Prisma.File to IFileEntity
 * @note use initFileEntity to create a new IFileEntity from scratch
 */
export interface IFileEntity {
  /**
   * Info: (20241023 - Murky)
   * @description file id from database, 0 means not created in database yet
   */
  id: number;

  /**
   * Info: (20241023 - Murky)
   * @description file name, it is random number generated by formittable
   */
  name: string;

  /**
   * Info: (20241023 - Murky)
   * @description file size in byte, can be transformed to string by transformBytesToFileSizeString
   */
  size: number;

  /**
   * Info: (20241023 - Murky)
   * @description file extension mimeType
   */
  mimeType: string;

  /**
   * Info: (20241023 - Murky)
   * @description determine which local folder this file is stored
   */
  type: FileFolder;

  /**
   * Info: (20241023 - Murky)
   * @description file url, can be used to get file from server or other storage
   */
  url: string;

  /**
   * Info: (20241023 - Murky)
   * @note need to be in seconds
   */
  createdAt: number;

  /**
   * Info: (20241023 - Murky)
   * @note need to be in seconds
   */
  updatedAt: number;

  /**
   * Info: (20241023 - Murky)
   * @note need to be in seconds, null if not deleted
   */
  deletedAt: number | null;

  /**
   * Info: (20241023 - Murky)
   * @description file buffer can be place here if get file from local storage or other storage
   */
  buffer?: Buffer;
  // ToDo: (20241023 - Murky) certificate
  // ToDo: (20241023 - Murky) companyImageFile
  // ToDo: (20241023 - Murky) ocrImageFile
  // ToDo: (20241023 - Murky) userImageFile
  // ToDo: (20241023 - Murky) projectImageFile
  // ToDo: (20241023 - Murky) registrationCertificateFile
  // ToDo: (20241023 - Murky) taxCertificateFile
  // ToDo: (20241023 - Murky) representativeIdCardFile
  // ToDo: (20241023 - Murky) kycPersonalIdFile
  // ToDo: (20241023 - Murky) kycCertificationFile
}
