import { TeamRole } from '@/interfaces/team';

export enum TeamPermissionAction {
  // Info: (20250313 - Tzuhan) 團隊操作權限
  INVITE_MEMBER = 'INVITE_MEMBER',
  LEAVE_TEAM = 'LEAVE_TEAM',
  DELETE_TEAM = 'DELETE_TEAM',
  MODIFY_NAME = 'MODIFY_NAME',
  MODIFY_IMAGE = 'MODIFY_IMAGE',
  MODIFY_ABOUT = 'MODIFY_ABOUT',
  MODIFY_PROFILE = 'MODIFY_PROFILE',
  MODIFY_BANK_ACCOUNT = 'MODIFY_BANK_ACCOUNT',
  MODIFY_PLAN = 'MODIFY_PLAN',
  VIEW_TEAM_INFO = 'VIEW_TEAM_INFO',
  VIEW_BANK_INFO = 'VIEW_BANK_INFO',
  VIEW_SUBSCRIPTION = 'VIEW_SUBSCRIPTION',

  // Info: (20250313 - Tzuhan) 帳本權限
  CREATE_ACCOUNT_BOOK = 'CREATE_ACCOUNT_BOOK',
  DELETE_ACCOUNT_BOOK = 'DELETE_ACCOUNT_BOOK',
  MODIFY_ACCOUNT_BOOK = 'MODIFY_ACCOUNT_BOOK',
  MODIFY_TAG = 'MODIFY_TAG',
  MODIFY_PRIVACY = 'MODIFY_PRIVACY',
  CREATE_PRIVATE_ACCOUNT_BOOK = 'CREATE_PRIVATE_ACCOUNT_BOOK',
  VIEW_PRIVATE_ACCOUNT_BOOK = 'VIEW_PRIVATE_ACCOUNT_BOOK',
  VIEW_PUBLIC_ACCOUNT_BOOK = 'VIEW_PUBLIC_ACCOUNT_BOOK',

  // Info: (20250313 - Tzuhan) 帳本轉移
  REQUEST_ACCOUNT_BOOK_TRANSFER = 'REQUEST_ACCOUNT_BOOK_TRANSFER',
  CANCEL_ACCOUNT_BOOK_TRANSFER = 'CANCEL_ACCOUNT_BOOK_TRANSFER',
  ACCEPT_ACCOUNT_BOOK_TRANSFER = 'ACCEPT_ACCOUNT_BOOK_TRANSFER',
  DECLINE_ACCOUNT_BOOK_TRANSFER = 'DECLINE_ACCOUNT_BOOK_TRANSFER',

  // Info: (20250313 - Tzuhan) 帳務相關
  BOOKKEEPING = 'BOOKKEEPING',
  ACCOUNTING_SETTING = 'ACCOUNTING_SETTING',

  // Info: (20250313 - Tzuhan) 變更角色
  CHANGE_TEAM_ROLE = 'CHANGE_TEAM_ROLE',
}

export interface IWhatTeamRoleCanDo {
  teamRole: TeamRole;
  canDo: TeamPermissionAction;
}

export interface ITeamRoleCanDo {
  teamRole: TeamRole;
  canDo: TeamPermissionAction;
  yesOrNo: boolean;
}

export interface IAlterTeamRole {
  teamRole: TeamRole;
  canAlter: TeamRole[];
}
