export const mockCertificateList = [
  {
    id: 1,
    inputOrOutput: 'input',
    certificateDate: 10000001,
    certificateNo: 'AB-12345678',
    currencyAlias: 'TWD',
    priceBeforeTax: 4000,
    taxRatio: 5,
    taxPrice: 200,
    totalPrice: 4200,
    counterPartyId: 1,
    invoiceType: 'triplicate_uniform_invoice',
    deductible: true,
    connectToId: null,
    name: 'invoice001.jpg',
    url: '/api/v2/certificate/1',
    type: 'invoice',
    connectToType: 'voucher',
    mimeTYpe: 'image/jpeg',
    size: '3.0 MB',
    uploadProgress: 50,
    aiResultId: 'douhvjax_-1',
    aiStatus: 'success',
    createAt: 10000000,
    updateAt: 10000000,
  },
];
