# .github/workflows/dependency-review.yml
name: Dependency Review
on:
  pull_request:
    branches: [ main, develop ]
permissions:
  contents: read
  pull-requests: write
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: critical
          vulnerability-check: true
          license-check: true
          comment-summary-in-pr: on-failure
